import type { Course } from './schema';

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;
const ytSearch = (q: string) =>
  `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`;
const dlai = (slug: string) => `https://www.deeplearning.ai/short-courses/${slug}/`;

type C = Course;

// Every entry is free (free to use or free to audit).
export const courses = {
  // ---------- P0 ----------
  baraaRoadmap: {
    id: 'baraa-roadmap',
    title: 'AI Engineer Roadmap: Built From 40,000 Real Job Ads',
    provider: 'Data with Baraa',
    url: yt('qKXUPI06tZo'),
    youtubeId: 'qKXUPI06tZo',
    format: 'video',
    hours: 0.6,
    interactivity: 1,
    visual: 4,
    handsOn: 1,
    popularity: 4,
    pitch: 'Skills ranked by what real job ads ask for. Your north star.',
  },
  babbarRoadmap: {
    id: 'babbar-roadmap',
    title: 'AI/ML Roadmap 2026: How to Become an AI Engineer',
    provider: 'Love Babbar',
    url: yt('YpQQY49xXhY'),
    youtubeId: 'YpQQY49xXhY',
    format: 'video',
    hours: 0.5,
    interactivity: 1,
    visual: 3,
    handsOn: 1,
    popularity: 5,
    pitch: 'Step-by-step 2026 roadmap from fundamentals to GenAI.',
  },
  karpathySoftware: {
    id: 'karpathy-software-changing',
    title: 'Software Is Changing (Again)',
    provider: 'Andrej Karpathy · YC',
    url: yt('LCEmiRjPEtQ'),
    youtubeId: 'LCEmiRjPEtQ',
    format: 'video',
    hours: 0.7,
    interactivity: 1,
    visual: 4,
    handsOn: 1,
    popularity: 5,
    pitch: 'Software 3.0: why LLM apps are a new kind of software.',
  },
  roadmapSh: {
    id: 'roadmapsh-ai-engineer',
    title: 'AI Engineer Roadmap (interactive map)',
    provider: 'roadmap.sh',
    url: 'https://roadmap.sh/ai-engineer',
    format: 'interactive',
    hours: 0.5,
    interactivity: 4,
    visual: 4,
    handsOn: 1,
    popularity: 5,
    pitch: 'Clickable community skill map. Great for spotting gaps.',
  },
  uv: {
    id: 'uv-docs',
    title: 'uv – fast Python package & project manager',
    provider: 'Astral',
    url: 'https://docs.astral.sh/uv/',
    format: 'docs',
    hours: 0.5,
    interactivity: 2,
    visual: 2,
    handsOn: 4,
    popularity: 4,
    pitch: 'pip + venv, 10–100× faster. The modern default.',
  },
  ollama: {
    id: 'ollama',
    title: 'Ollama – run LLMs locally',
    provider: 'Ollama',
    url: 'https://ollama.com',
    format: 'docs',
    hours: 0.5,
    interactivity: 3,
    visual: 2,
    handsOn: 5,
    popularity: 5,
    pitch: 'Free, offline Llama / Qwen / Gemma on your laptop.',
  },
  aiStudio: {
    id: 'google-ai-studio',
    title: 'Google AI Studio (Gemini free tier)',
    provider: 'Google',
    url: 'https://aistudio.google.com',
    format: 'interactive',
    hours: 0.5,
    interactivity: 4,
    visual: 3,
    handsOn: 4,
    popularity: 4,
    pitch: 'Playground + free API key in two minutes.',
  },
  githubModels: {
    id: 'github-models',
    title: 'GitHub Models',
    provider: 'GitHub',
    url: 'https://github.com/marketplace/models',
    format: 'interactive',
    hours: 0.5,
    interactivity: 3,
    visual: 2,
    handsOn: 4,
    popularity: 3,
    pitch: 'Free, rate-limited GPT / Llama / Mistral via your GitHub login.',
  },

  // ---------- P1 ----------
  pydantic: {
    id: 'pydantic-docs',
    title: 'Pydantic – Concepts',
    provider: 'Pydantic docs',
    url: 'https://docs.pydantic.dev/latest/',
    format: 'docs',
    hours: 2,
    interactivity: 2,
    visual: 2,
    handsOn: 4,
    popularity: 5,
    pitch: 'The validation layer used by FastAPI, LangChain and every LLM SDK.',
  },
  pytest: {
    id: 'pytest-start',
    title: 'pytest – Get Started',
    provider: 'pytest docs',
    url: 'https://docs.pytest.org/en/stable/getting-started.html',
    format: 'docs',
    hours: 1,
    interactivity: 2,
    visual: 2,
    handsOn: 5,
    popularity: 5,
    pitch: 'Your test-case mindset, as Python code.',
  },
  kagglePandas: {
    id: 'kaggle-pandas',
    title: 'Kaggle Learn: Pandas',
    provider: 'Kaggle',
    url: 'https://www.kaggle.com/learn/pandas',
    format: 'interactive',
    hours: 4,
    interactivity: 5,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    certificate: true,
    pitch: 'In-browser notebooks with instant checks. Free certificate.',
    lessons: [
      'Creating, reading & writing',
      'Indexing, selecting & assigning',
      'Summary functions & maps',
      'Grouping & sorting',
      'Data types & missing values',
      'Renaming & combining',
    ],
  },
  realPythonAsync: {
    id: 'realpython-async',
    title: 'Async IO in Python: A Complete Walkthrough',
    provider: 'Real Python',
    url: 'https://realpython.com/async-io-python/',
    format: 'article',
    hours: 1.5,
    interactivity: 2,
    visual: 3,
    handsOn: 4,
    popularity: 5,
    pitch: 'The clearest async/await guide, with runnable examples.',
  },
  httpx: {
    id: 'httpx-docs',
    title: 'HTTPX – sync & async HTTP client',
    provider: 'HTTPX docs',
    url: 'https://www.python-httpx.org/',
    format: 'docs',
    hours: 1,
    interactivity: 2,
    visual: 2,
    handsOn: 4,
    popularity: 4,
    pitch: 'Modern requests-style client with async, timeouts and retries.',
  },
  fastapi: {
    id: 'fastapi-tutorial',
    title: 'FastAPI Tutorial – User Guide',
    provider: 'FastAPI docs',
    url: 'https://fastapi.tiangolo.com/tutorial/',
    format: 'docs',
    hours: 4,
    interactivity: 3,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Best-in-class official tutorial. Build as you read.',
    lessons: [
      'First steps & path params',
      'Query params & request body',
      'Response models',
      'Dependencies',
      'Error handling',
      'Background tasks & testing',
    ],
  },
  fccFastapi: {
    id: 'fcc-python-api',
    title: 'Python API Development – Comprehensive Course',
    provider: 'freeCodeCamp',
    url: yt('0sOvCWFmrtA'),
    youtubeId: '0sOvCWFmrtA',
    format: 'video',
    hours: 19,
    interactivity: 1,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Pick chapters only: FastAPI basics, Pydantic, auth, testing.',
    lessons: ['FastAPI basics', 'Pydantic schemas', 'Database & ORM', 'Auth (JWT)', 'Testing'],
  },

  // ---------- P2 ----------
  googleMlcc: {
    id: 'google-mlcc',
    title: 'Machine Learning Crash Course',
    provider: 'Google',
    url: 'https://developers.google.com/machine-learning/crash-course',
    format: 'interactive',
    hours: 15,
    interactivity: 5,
    visual: 5,
    handsOn: 4,
    popularity: 5,
    pitch: 'Animated visuals + interactive exercises. Pick the core modules.',
    lessons: [
      'Linear regression',
      'Logistic regression',
      'Classification & metrics',
      'Numerical & categorical data',
      'Datasets, generalization & overfitting',
      'Neural networks',
      'Embeddings',
      'Intro to LLMs',
      'Production ML systems',
    ],
  },
  kaggleIntroMl: {
    id: 'kaggle-intro-ml',
    title: 'Kaggle Learn: Intro to Machine Learning',
    provider: 'Kaggle',
    url: 'https://www.kaggle.com/learn/intro-to-machine-learning',
    format: 'interactive',
    hours: 3,
    interactivity: 5,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    certificate: true,
    pitch: 'Train your first model in the browser. Free certificate.',
    lessons: [
      'How models work',
      'Basic data exploration',
      'Your first ML model',
      'Model validation',
      'Underfitting & overfitting',
      'Random forests',
      'Machine learning competitions',
    ],
  },
  r2d3: {
    id: 'r2d3-visual-ml',
    title: 'A Visual Introduction to Machine Learning',
    provider: 'R2D3',
    url: 'https://r2d3.us/visual-intro-to-machine-learning-part-1/',
    format: 'interactive',
    hours: 0.3,
    interactivity: 4,
    visual: 5,
    handsOn: 1,
    popularity: 4,
    pitch: 'Scroll-driven animated explainer. Pure visual joy.',
  },
  statquest: {
    id: 'statquest',
    title: 'StatQuest – ML fundamentals',
    provider: 'Josh Starmer · YouTube',
    url: 'https://www.youtube.com/@statquest',
    format: 'video',
    hours: 3,
    interactivity: 1,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'Clearly explained, with doodles and songs. Pick the ML basics playlist.',
  },
  nn3b1b: {
    id: '3b1b-neural-network',
    title: 'But what is a neural network?',
    provider: '3Blue1Brown',
    url: yt('aircAruvnKk'),
    youtubeId: 'aircAruvnKk',
    format: 'video',
    hours: 0.3,
    interactivity: 1,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'The most famous visual explanation of neural nets.',
  },
  gd3b1b: {
    id: '3b1b-gradient-descent',
    title: 'Gradient descent, how neural networks learn',
    provider: '3Blue1Brown',
    url: yt('IHZwWFHWa-w'),
    youtubeId: 'IHZwWFHWa-w',
    format: 'video',
    hours: 0.4,
    interactivity: 1,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'See "learning" as rolling downhill on an error surface.',
  },
  tfPlayground: {
    id: 'tf-playground',
    title: 'TensorFlow Playground',
    provider: 'Google',
    url: 'https://playground.tensorflow.org',
    format: 'interactive',
    hours: 1,
    interactivity: 5,
    visual: 5,
    handsOn: 3,
    popularity: 5,
    pitch: 'Tinker with a live neural net in your browser. Addictive.',
  },
  micrograd: {
    id: 'karpathy-micrograd',
    title: 'Neural networks & backprop: building micrograd',
    provider: 'Andrej Karpathy',
    url: yt('VMj-3S1tku0'),
    youtubeId: 'VMj-3S1tku0',
    format: 'video',
    hours: 2.5,
    interactivity: 2,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Build backprop from scratch, code-along. Legendary.',
  },
  fastai: {
    id: 'fastai-practical-dl',
    title: 'Practical Deep Learning for Coders',
    provider: 'fast.ai',
    url: 'https://course.fast.ai',
    format: 'course',
    hours: 8,
    interactivity: 3,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Top-down: train a real model in lesson 1. Do lessons 1–2.',
    lessons: ['Lesson 1 · Getting started', 'Lesson 2 · Deployment'],
  },
  karpathyTokenizer: {
    id: 'karpathy-tokenizer',
    title: "Let's build the GPT Tokenizer",
    provider: 'Andrej Karpathy',
    url: yt('zduSFxRajkE'),
    youtubeId: 'zduSFxRajkE',
    format: 'video',
    hours: 2.2,
    interactivity: 2,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Why LLMs struggle with spelling and maths — built from scratch.',
  },
  tiktokenizer: {
    id: 'tiktokenizer',
    title: 'Tiktokenizer – see tokens live',
    provider: 'Tiktokenizer',
    url: 'https://tiktokenizer.vercel.app',
    format: 'interactive',
    hours: 0.3,
    interactivity: 5,
    visual: 4,
    handsOn: 2,
    popularity: 3,
    pitch: 'Type text, watch it split into coloured tokens instantly.',
  },
  word2vec: {
    id: 'alammar-word2vec',
    title: 'The Illustrated Word2vec',
    provider: 'Jay Alammar',
    url: 'https://jalammar.github.io/illustrated-word2vec/',
    format: 'article',
    hours: 0.7,
    interactivity: 1,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'Embeddings explained almost entirely in pictures.',
  },
  hfLlmCourse: {
    id: 'hf-llm-course',
    title: 'Hugging Face LLM Course',
    provider: 'Hugging Face',
    url: 'https://huggingface.co/learn/llm-course',
    format: 'course',
    hours: 6,
    interactivity: 4,
    visual: 3,
    handsOn: 4,
    popularity: 5,
    certificate: true,
    pitch: 'Transformers, tokenizers, pipelines, fine-tuning. Runnable in Colab.',
    lessons: [
      'Transformer models',
      'Using Transformers',
      'Tokenizers',
      'Fine-tuning a pretrained model',
      'Sharing models & datasets',
    ],
  },

  // ---------- P3 ----------
  karpathyIntroLlm: {
    id: 'karpathy-intro-llm',
    title: '[1hr Talk] Intro to Large Language Models',
    provider: 'Andrej Karpathy',
    url: yt('zjkBMFhNj_g'),
    youtubeId: 'zjkBMFhNj_g',
    format: 'video',
    hours: 1,
    interactivity: 1,
    visual: 4,
    handsOn: 1,
    popularity: 5,
    pitch: 'The best single hour on what LLMs are and where they are going.',
  },
  llmBrief3b1b: {
    id: '3b1b-llm-brief',
    title: 'Large Language Models explained briefly',
    provider: '3Blue1Brown',
    url: yt('LPZh9BOjkQs'),
    youtubeId: 'LPZh9BOjkQs',
    format: 'video',
    hours: 0.15,
    interactivity: 1,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: '8 minutes. Beautiful animations. Start here.',
  },
  transformers3b1b: {
    id: '3b1b-transformers',
    title: 'Transformers, the tech behind LLMs',
    provider: '3Blue1Brown',
    url: yt('wjZofJX0v4M'),
    youtubeId: 'wjZofJX0v4M',
    format: 'video',
    hours: 0.5,
    interactivity: 1,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'Visual tour of how a GPT turns words into predictions.',
  },
  attention3b1b: {
    id: '3b1b-attention',
    title: 'Attention in transformers, step-by-step',
    provider: '3Blue1Brown',
    url: yt('eMlx5fFNoYc'),
    youtubeId: 'eMlx5fFNoYc',
    format: 'video',
    hours: 0.45,
    interactivity: 1,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'The key idea behind LLMs, animated.',
  },
  facts3b1b: {
    id: '3b1b-llm-facts',
    title: 'How might LLMs store facts',
    provider: '3Blue1Brown',
    url: yt('9-Jl0dxWQs8'),
    youtubeId: '9-Jl0dxWQs8',
    format: 'video',
    hours: 0.4,
    interactivity: 1,
    visual: 5,
    handsOn: 1,
    popularity: 4,
    pitch: 'Where "knowledge" lives inside the network.',
  },
  transformerExplainer: {
    id: 'transformer-explainer',
    title: 'Transformer Explainer (live GPT-2 in browser)',
    provider: 'Georgia Tech Polo Club',
    url: 'https://poloclub.github.io/transformer-explainer/',
    format: 'interactive',
    hours: 0.5,
    interactivity: 5,
    visual: 5,
    handsOn: 2,
    popularity: 4,
    pitch: 'Type a prompt and watch attention flow through a real model.',
  },
  bbycroft: {
    id: 'bbycroft-llm-viz',
    title: 'LLM Visualization (3D walkthrough)',
    provider: 'Brendan Bycroft',
    url: 'https://bbycroft.net/llm',
    format: 'interactive',
    hours: 1,
    interactivity: 5,
    visual: 5,
    handsOn: 1,
    popularity: 4,
    pitch: 'Fly through a GPT in 3D, layer by layer.',
  },
  karpathyDeepDive: {
    id: 'karpathy-deep-dive',
    title: 'Deep Dive into LLMs like ChatGPT',
    provider: 'Andrej Karpathy',
    url: yt('7xTGNNLPyMI'),
    youtubeId: '7xTGNNLPyMI',
    format: 'video',
    hours: 3.5,
    interactivity: 1,
    visual: 4,
    handsOn: 1,
    popularity: 5,
    pitch: 'Full stack of LLM training: pre-training, SFT, RL. Watch in parts.',
    lessons: [
      'Pre-training data & tokenization',
      'Neural net internals & inference',
      'Post-training: SFT',
      'Hallucinations & tool use',
      'Reinforcement learning & RLHF',
    ],
  },
  karpathyHowIUse: {
    id: 'karpathy-how-i-use-llms',
    title: 'How I use LLMs',
    provider: 'Andrej Karpathy',
    url: yt('EWvNQjAaOHw'),
    youtubeId: 'EWvNQjAaOHw',
    format: 'video',
    hours: 2.2,
    interactivity: 1,
    visual: 4,
    handsOn: 3,
    popularity: 5,
    pitch: 'Practical tour of tools, thinking models, search, code and more.',
  },
  stateOfGpt: {
    id: 'state-of-gpt',
    title: 'State of GPT',
    provider: 'Andrej Karpathy · Microsoft Build',
    url: yt('bZQun8Y4L2A'),
    youtubeId: 'bZQun8Y4L2A',
    format: 'video',
    hours: 0.7,
    interactivity: 1,
    visual: 4,
    handsOn: 1,
    popularity: 5,
    pitch: 'How GPT assistants are trained + how to use them effectively.',
  },
  buildGpt: {
    id: 'karpathy-build-gpt',
    title: "Let's build GPT: from scratch, in code",
    provider: 'Andrej Karpathy',
    url: yt('kCc8FmEb1nY'),
    youtubeId: 'kCc8FmEb1nY',
    format: 'video',
    hours: 2,
    interactivity: 2,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Stretch goal: code a mini transformer yourself.',
  },
  dlaiTransformerLlms: {
    id: 'dlai-how-transformer-llms-work',
    title: 'How Transformer LLMs Work',
    provider: 'DeepLearning.AI',
    url: dlai('how-transformer-llms-work'),
    format: 'course',
    hours: 1.5,
    interactivity: 3,
    visual: 5,
    handsOn: 3,
    popularity: 4,
    pitch: 'Jay Alammar & Maarten Grootendorst, illustrated and hands-on.',
  },
  dlaiPromptEng: {
    id: 'dlai-prompt-eng-devs',
    title: 'ChatGPT Prompt Engineering for Developers',
    provider: 'DeepLearning.AI × OpenAI',
    url: dlai('chatgpt-prompt-engineering-for-developers'),
    format: 'course',
    hours: 1.5,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Andrew Ng + OpenAI. In-browser notebooks. The classic.',
    lessons: [
      'Guidelines',
      'Iterative prompt development',
      'Summarizing',
      'Inferring',
      'Transforming',
      'Expanding',
      'Chatbot',
    ],
  },
  anthropicPrompt: {
    id: 'anthropic-prompt-tutorial',
    title: 'Interactive Prompt Engineering Tutorial',
    provider: 'Anthropic',
    url: 'https://github.com/anthropics/prompt-eng-interactive-tutorial',
    format: 'notebook',
    hours: 4,
    interactivity: 5,
    visual: 2,
    handsOn: 5,
    popularity: 4,
    pitch: '9 chapters of exercises with instant feedback.',
    lessons: [
      'Basic prompt structure',
      'Being clear and direct',
      'Assigning roles',
      'Separating data from instructions',
      'Formatting output',
      'Thinking step by step',
      'Using examples',
      'Avoiding hallucinations',
      'Complex prompts from scratch',
    ],
  },
  promptingGuide: {
    id: 'prompting-guide',
    title: 'Prompt Engineering Guide',
    provider: 'DAIR.AI',
    url: 'https://www.promptingguide.ai',
    format: 'docs',
    hours: 2,
    interactivity: 2,
    visual: 3,
    handsOn: 2,
    popularity: 5,
    pitch: 'The reference for every technique: CoT, ReAct, few-shot…',
  },
  learnPrompting: {
    id: 'learn-prompting',
    title: 'Learn Prompting',
    provider: 'Learn Prompting',
    url: 'https://learnprompting.org',
    format: 'course',
    hours: 3,
    interactivity: 3,
    visual: 3,
    handsOn: 3,
    popularity: 4,
    pitch: 'Beginner-friendly free docs course with examples.',
  },
  geminiDocs: {
    id: 'gemini-api-docs',
    title: 'Gemini API – quickstart & structured output',
    provider: 'Google AI for Developers',
    url: 'https://ai.google.dev/gemini-api/docs',
    format: 'docs',
    hours: 2,
    interactivity: 3,
    visual: 2,
    handsOn: 5,
    popularity: 4,
    pitch: 'Free-tier API: JSON mode, function calling, embeddings.',
  },
  openaiStructured: {
    id: 'openai-structured-outputs',
    title: 'Structured Outputs guide',
    provider: 'OpenAI docs',
    url: 'https://platform.openai.com/docs/guides/structured-outputs',
    format: 'docs',
    hours: 1,
    interactivity: 2,
    visual: 2,
    handsOn: 4,
    popularity: 5,
    pitch: 'JSON-schema-guaranteed responses. Same idea on Azure OpenAI.',
  },
  instructor: {
    id: 'instructor',
    title: 'Instructor – structured outputs with Pydantic',
    provider: 'Instructor',
    url: 'https://python.useinstructor.com',
    format: 'docs',
    hours: 1.5,
    interactivity: 2,
    visual: 2,
    handsOn: 5,
    popularity: 4,
    pitch: 'Pydantic-first structured output for any LLM, with retries.',
  },
  dlaiFunctionsTools: {
    id: 'dlai-functions-tools-agents',
    title: 'Functions, Tools and Agents with LangChain',
    provider: 'DeepLearning.AI × LangChain',
    url: dlai('functions-tools-agents-langchain'),
    format: 'course',
    hours: 1.5,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    pitch: 'Function calling → tools → your first agent.',
  },
  awesomeLlmApps: {
    id: 'awesome-llm-apps',
    title: 'Awesome LLM Apps',
    provider: 'GitHub · Shubham Saboo',
    url: 'https://github.com/Shubhamsaboo/awesome-llm-apps',
    format: 'notebook',
    hours: 1,
    interactivity: 2,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Inspiration: 100+ runnable RAG and agent app examples.',
  },
  duckdb: {
    id: 'duckdb-docs',
    title: 'DuckDB – in-process SQL',
    provider: 'DuckDB docs',
    url: 'https://duckdb.org/docs/',
    format: 'docs',
    hours: 0.5,
    interactivity: 3,
    visual: 2,
    handsOn: 5,
    popularity: 4,
    pitch: 'Run generated SQL locally on CSV/Parquet. Zero setup.',
  },

  // ---------- P4 ----------
  dlaiVectorDb: {
    id: 'dlai-vector-databases',
    title: 'Vector Databases: from Embeddings to Applications',
    provider: 'DeepLearning.AI × Weaviate',
    url: dlai('vector-databases-embeddings-applications'),
    format: 'course',
    hours: 1,
    interactivity: 4,
    visual: 4,
    handsOn: 5,
    popularity: 4,
    pitch: 'Embeddings, ANN search, hybrid search — hands-on.',
  },
  pineconeLearn: {
    id: 'pinecone-learn',
    title: 'Pinecone Learning Center',
    provider: 'Pinecone',
    url: 'https://www.pinecone.io/learn/',
    format: 'article',
    hours: 3,
    interactivity: 2,
    visual: 5,
    handsOn: 2,
    popularity: 4,
    pitch: 'Beautifully illustrated guides to vector search & RAG.',
  },
  chroma: {
    id: 'chroma-docs',
    title: 'Chroma – open-source vector DB',
    provider: 'Chroma docs',
    url: 'https://docs.trychroma.com',
    format: 'docs',
    hours: 1,
    interactivity: 3,
    visual: 2,
    handsOn: 5,
    popularity: 4,
    pitch: 'pip install, 5 lines to a working vector store.',
  },
  azureAiSearch: {
    id: 'azure-ai-search',
    title: 'Azure AI Search – vector & hybrid search',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/azure/search/',
    format: 'docs',
    hours: 2,
    interactivity: 2,
    visual: 2,
    handsOn: 3,
    popularity: 3,
    pitch: 'The Azure-native vector store for your capstone.',
  },
  fccRag: {
    id: 'fcc-rag-from-scratch',
    title: 'Learn RAG From Scratch (LangChain engineer)',
    provider: 'freeCodeCamp',
    url: yt('sVcwVQRHIc8'),
    youtubeId: 'sVcwVQRHIc8',
    format: 'video',
    hours: 2.5,
    interactivity: 1,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Lance Martin builds every RAG technique step by step.',
    lessons: [
      'Overview: indexing, retrieval, generation',
      'Query translation (multi-query, RAG-fusion)',
      'Routing & query construction',
      'Indexing (multi-representation, RAPTOR)',
      'Retrieval (re-ranking, CRAG) & generation',
    ],
  },
  dlaiChatData: {
    id: 'dlai-langchain-chat-data',
    title: 'LangChain: Chat with Your Data',
    provider: 'DeepLearning.AI × LangChain',
    url: dlai('langchain-chat-with-your-data'),
    format: 'course',
    hours: 1,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Loaders → splitters → vector store → Q&A → chat. In 1 hour.',
  },
  courseraRag: {
    id: 'coursera-rag',
    title: 'Retrieval Augmented Generation (RAG)',
    provider: 'DeepLearning.AI · Coursera (audit)',
    url: 'https://www.coursera.org/learn/retrieval-augmented-generation-rag',
    format: 'course',
    hours: 12,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    pitch: 'The full, production-focused RAG course. Free to audit.',
    lessons: [
      'RAG overview',
      'Information retrieval & search',
      'Vector databases',
      'LLMs & text generation',
      'RAG systems in production',
    ],
  },
  llamaIndex: {
    id: 'llamaindex-docs',
    title: 'LlamaIndex – starter tutorials',
    provider: 'LlamaIndex docs',
    url: 'https://docs.llamaindex.ai',
    format: 'docs',
    hours: 2,
    interactivity: 3,
    visual: 2,
    handsOn: 5,
    popularity: 4,
    pitch: 'Data-first framework for RAG over documents.',
  },
  dlaiAdvancedRag: {
    id: 'dlai-advanced-rag',
    title: 'Building and Evaluating Advanced RAG',
    provider: 'DeepLearning.AI × LlamaIndex',
    url: dlai('building-evaluating-advanced-rag'),
    format: 'course',
    hours: 1,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    pitch: 'Sentence-window & auto-merging retrieval + the RAG triad.',
  },
  dlaiAdvancedRetrieval: {
    id: 'dlai-advanced-retrieval',
    title: 'Advanced Retrieval for AI with Chroma',
    provider: 'DeepLearning.AI × Chroma',
    url: dlai('advanced-retrieval-for-ai'),
    format: 'course',
    hours: 1,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    pitch: 'Query expansion, cross-encoder re-ranking, embedding adapters.',
  },
  ragas: {
    id: 'ragas-docs',
    title: 'Ragas – evaluate RAG pipelines',
    provider: 'Ragas docs',
    url: 'https://docs.ragas.io',
    format: 'docs',
    hours: 1.5,
    interactivity: 2,
    visual: 2,
    handsOn: 5,
    popularity: 4,
    pitch: 'Faithfulness, context precision/recall — as code.',
  },
  dlaiAgenticRag: {
    id: 'dlai-agentic-rag-llamaindex',
    title: 'Building Agentic RAG with LlamaIndex',
    provider: 'DeepLearning.AI × LlamaIndex',
    url: dlai('building-agentic-rag-with-llamaindex'),
    format: 'course',
    hours: 1,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    pitch: 'Bridge to agents: RAG that decides how to search.',
  },
  streamlit: {
    id: 'streamlit-docs',
    title: 'Streamlit – build a chat app',
    provider: 'Streamlit docs',
    url: 'https://docs.streamlit.io',
    format: 'docs',
    hours: 1.5,
    interactivity: 3,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'A chat UI in about 30 lines of Python.',
  },

  // ---------- P5 ----------
  hfAgents: {
    id: 'hf-agents-course',
    title: 'Hugging Face AI Agents Course',
    provider: 'Hugging Face',
    url: 'https://huggingface.co/learn/agents-course',
    format: 'course',
    hours: 20,
    interactivity: 5,
    visual: 4,
    handsOn: 5,
    popularity: 5,
    certificate: true,
    pitch: 'The most popular free agents course. Quizzes, Spaces, certificate.',
    lessons: [
      'Unit 0 · Welcome & setup',
      'Unit 1 · What are agents? (Thought → Action → Observation)',
      'Unit 1 · First agent + quiz',
      'Unit 2.1 · smolagents',
      'Unit 2.2 · LlamaIndex agents',
      'Unit 2.3 · LangGraph',
      'Unit 3 · Agentic RAG use case',
      'Unit 4 · Final project & certificate',
    ],
  },
  anthropicAgents: {
    id: 'anthropic-effective-agents',
    title: 'Building Effective Agents',
    provider: 'Anthropic',
    url: 'https://www.anthropic.com/engineering/building-effective-agents',
    format: 'article',
    hours: 0.5,
    interactivity: 1,
    visual: 4,
    handsOn: 1,
    popularity: 5,
    pitch: 'The most-cited guide on when (and when not) to use agents.',
  },
  msAgentsBeginners: {
    id: 'ms-ai-agents-beginners',
    title: 'AI Agents for Beginners',
    provider: 'Microsoft · GitHub',
    url: 'https://github.com/microsoft/ai-agents-for-beginners',
    format: 'course',
    hours: 10,
    interactivity: 4,
    visual: 4,
    handsOn: 5,
    popularity: 5,
    pitch: 'Short video + code lessons. Azure-friendly. Great visuals.',
    lessons: [
      'Intro to AI agents',
      'Exploring agentic frameworks',
      'Agentic design patterns',
      'Tool use',
      'Agentic RAG',
      'Building trustworthy agents',
      'Planning',
      'Multi-agent',
      'Metacognition',
      'AI agents in production',
    ],
  },
  ngAgenticTalk: {
    id: 'ng-agentic-workflows-talk',
    title: "What's next for AI agentic workflows",
    provider: 'Andrew Ng · Sequoia',
    url: yt('sal78ACtGTc'),
    youtubeId: 'sal78ACtGTc',
    format: 'video',
    hours: 0.25,
    interactivity: 1,
    visual: 3,
    handsOn: 1,
    popularity: 5,
    pitch: 'The talk that popularised the 4 agentic design patterns.',
  },
  ngAgenticAi: {
    id: 'dlai-agentic-ai',
    title: 'Agentic AI (Andrew Ng)',
    provider: 'DeepLearning.AI',
    url: 'https://www.deeplearning.ai/courses/agentic-ai/',
    format: 'course',
    hours: 6,
    interactivity: 4,
    visual: 4,
    handsOn: 5,
    popularity: 5,
    pitch: 'Framework-agnostic agentic patterns + evals and error analysis.',
    lessons: [
      'Intro to agentic workflows',
      'Reflection design pattern',
      'Tool use',
      'Practical tips: evals & error analysis',
      'Planning & multi-agent patterns',
    ],
  },
  kaggleAgents: {
    id: 'kaggle-5day-agents',
    title: '5-Day AI Agents Intensive (Google × Kaggle)',
    provider: 'Kaggle · YouTube',
    url: ytSearch('Kaggle 5-Day AI Agents Intensive Google'),
    format: 'video',
    hours: 5,
    interactivity: 3,
    visual: 3,
    handsOn: 4,
    popularity: 4,
    pitch: 'Livestreams + codelabs: tools, memory, evaluation, production.',
  },
  openaiAgentsSdk: {
    id: 'openai-agents-sdk',
    title: 'OpenAI Agents SDK',
    provider: 'OpenAI docs',
    url: 'https://openai.github.io/openai-agents-python/',
    format: 'docs',
    hours: 2,
    interactivity: 2,
    visual: 2,
    handsOn: 5,
    popularity: 4,
    pitch: 'Lightweight agents, handoffs and guardrails in Python.',
  },
  langchainAcademy: {
    id: 'langchain-academy-langgraph',
    title: 'Introduction to LangGraph',
    provider: 'LangChain Academy',
    url: 'https://academy.langchain.com/courses/intro-to-langgraph',
    format: 'course',
    hours: 8,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Official free course by the LangGraph team. Video + notebooks.',
    lessons: [
      'Module 0 · Setup',
      'Module 1 · Graphs, routers, agents, memory',
      'Module 2 · State & memory',
      'Module 3 · Human-in-the-loop',
      'Module 4 · Parallelization, sub-graphs, map-reduce',
      'Module 5 · Long-term memory',
      'Module 6 · Deployment',
    ],
  },
  dlaiLanggraph: {
    id: 'dlai-agents-langgraph',
    title: 'AI Agents in LangGraph',
    provider: 'DeepLearning.AI × LangChain',
    url: dlai('ai-agents-in-langgraph'),
    format: 'course',
    hours: 1.5,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Build an agent from scratch, then rebuild it in LangGraph.',
  },
  langgraphDocs: {
    id: 'langgraph-docs',
    title: 'LangGraph docs & tutorials',
    provider: 'LangChain',
    url: 'https://langchain-ai.github.io/langgraph/',
    format: 'docs',
    hours: 2,
    interactivity: 2,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    pitch: 'Reference for graphs, persistence, interrupts, multi-agent.',
  },
  dlaiCrewai: {
    id: 'dlai-crewai',
    title: 'Multi AI Agent Systems with crewAI',
    provider: 'DeepLearning.AI × crewAI',
    url: dlai('multi-ai-agent-systems-with-crewai'),
    format: 'course',
    hours: 2.5,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Role-based agent teams — fastest way to "get" multi-agent.',
  },
  hfMcp: {
    id: 'hf-mcp-course',
    title: 'Hugging Face MCP Course',
    provider: 'Hugging Face',
    url: 'https://huggingface.co/learn/mcp-course',
    format: 'course',
    hours: 6,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    certificate: true,
    pitch: 'Build MCP servers & clients end-to-end. Free certificate.',
  },
  dlaiMcp: {
    id: 'dlai-mcp-anthropic',
    title: 'MCP: Build Rich-Context AI Apps with Anthropic',
    provider: 'DeepLearning.AI × Anthropic',
    url: dlai('mcp-build-rich-context-ai-apps-with-anthropic'),
    format: 'course',
    hours: 1.5,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Build and connect MCP servers in about 90 minutes.',
  },
  mcpDocs: {
    id: 'mcp-docs',
    title: 'Model Context Protocol docs',
    provider: 'modelcontextprotocol.io',
    url: 'https://modelcontextprotocol.io',
    format: 'docs',
    hours: 1.5,
    interactivity: 2,
    visual: 3,
    handsOn: 4,
    popularity: 5,
    pitch: 'Official spec, concepts and quickstarts.',
  },

  // ---------- P6 ----------
  dlaiTestingLlmops: {
    id: 'dlai-automated-testing-llmops',
    title: 'Automated Testing for LLMOps',
    provider: 'DeepLearning.AI × CircleCI',
    url: dlai('automated-testing-llmops'),
    format: 'course',
    hours: 1,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    pitch: 'Made for you: rule-based & model-graded evals in CI.',
  },
  dlaiEvalDebug: {
    id: 'dlai-evaluating-debugging-genai',
    title: 'Evaluating and Debugging Generative AI',
    provider: 'DeepLearning.AI × W&B',
    url: dlai('evaluating-debugging-generative-ai'),
    format: 'course',
    hours: 1,
    interactivity: 4,
    visual: 3,
    handsOn: 4,
    popularity: 4,
    pitch: 'Tracking, tracing and evaluating LLM experiments.',
  },
  deepeval: {
    id: 'deepeval-docs',
    title: 'DeepEval – unit tests for LLMs',
    provider: 'Confident AI',
    url: 'https://deepeval.com',
    format: 'docs',
    hours: 2,
    interactivity: 2,
    visual: 2,
    handsOn: 5,
    popularity: 4,
    pitch: 'pytest-style assertions for LLM outputs, RAG and agents.',
  },
  hamelEvals: {
    id: 'hamel-evals',
    title: 'Your AI Product Needs Evals',
    provider: 'Hamel Husain',
    url: 'https://hamel.dev/blog/posts/evals/',
    format: 'article',
    hours: 0.7,
    interactivity: 1,
    visual: 3,
    handsOn: 2,
    popularity: 5,
    pitch: 'The most-shared practical essay on LLM evals.',
  },
  owaspLlm: {
    id: 'owasp-llm-top10',
    title: 'OWASP Top 10 for LLM Applications',
    provider: 'OWASP GenAI',
    url: 'https://genai.owasp.org',
    format: 'docs',
    hours: 1,
    interactivity: 2,
    visual: 3,
    handsOn: 2,
    popularity: 5,
    pitch: 'The security checklist: injection, data leaks, excessive agency.',
  },
  dlaiQualitySafety: {
    id: 'dlai-quality-safety-llm',
    title: 'Quality and Safety for LLM Applications',
    provider: 'DeepLearning.AI × WhyLabs',
    url: dlai('quality-safety-llm-applications'),
    format: 'course',
    hours: 1,
    interactivity: 4,
    visual: 3,
    handsOn: 4,
    popularity: 4,
    pitch: 'Detect hallucinations, leaks, jailbreaks and toxicity.',
  },
  langfuse: {
    id: 'langfuse-docs',
    title: 'Langfuse – LLM tracing & observability',
    provider: 'Langfuse',
    url: 'https://langfuse.com/docs',
    format: 'docs',
    hours: 1.5,
    interactivity: 3,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    pitch: 'Open-source traces, costs and evals. Free cloud tier.',
  },
  nanaDocker: {
    id: 'nana-docker',
    title: 'Docker Tutorial for Beginners [3 hours]',
    provider: 'TechWorld with Nana',
    url: yt('3c-iBn73dDE'),
    youtubeId: '3c-iBn73dDE',
    format: 'video',
    hours: 3,
    interactivity: 1,
    visual: 4,
    handsOn: 4,
    popularity: 5,
    pitch: 'Animated diagrams + demos. The go-to Docker intro.',
    lessons: ['Containers vs VMs', 'Images & containers', 'Dockerfile', 'Docker Compose', 'Volumes & registry'],
  },
  dockerGetStarted: {
    id: 'docker-get-started',
    title: 'Docker – Get started',
    provider: 'Docker docs',
    url: 'https://docs.docker.com/get-started/',
    format: 'docs',
    hours: 2,
    interactivity: 3,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Official hands-on workshop.',
  },
  msGenAiBeginners: {
    id: 'ms-genai-beginners',
    title: 'Generative AI for Beginners',
    provider: 'Microsoft · GitHub',
    url: 'https://github.com/microsoft/generative-ai-for-beginners',
    format: 'course',
    hours: 12,
    interactivity: 3,
    visual: 4,
    handsOn: 5,
    popularity: 5,
    pitch: '21 video + code lessons. Azure OpenAI throughout.',
    lessons: [
      'Intro to GenAI & LLMs',
      'Exploring & comparing LLMs',
      'Using GenAI responsibly',
      'Prompt engineering fundamentals',
      'Building search apps (embeddings)',
      'Building chat apps',
      'Function calling',
      'RAG & vector databases',
      'LLMOps / app lifecycle',
      'Securing GenAI apps',
    ],
  },
  azureFoundry: {
    id: 'azure-ai-foundry',
    title: 'Azure AI Foundry documentation',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/azure/ai-foundry/',
    format: 'docs',
    hours: 3,
    interactivity: 3,
    visual: 3,
    handsOn: 4,
    popularity: 4,
    pitch: 'Deploy models, build agents, run evals — in Azure.',
  },
  azureContainerApps: {
    id: 'azure-container-apps',
    title: 'Azure Container Apps – quickstarts',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/azure/container-apps/',
    format: 'docs',
    hours: 2,
    interactivity: 2,
    visual: 2,
    handsOn: 5,
    popularity: 4,
    pitch: 'Serverless containers that scale to zero.',
  },
  msLearnGenAi: {
    id: 'ms-learn-genai-paths',
    title: 'Microsoft Learn – Generative AI on Azure paths',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/training/browse/?terms=generative%20ai%20azure',
    format: 'interactive',
    hours: 6,
    interactivity: 4,
    visual: 3,
    handsOn: 4,
    popularity: 4,
    pitch: 'Free modules with guided labs. Pick the AI Foundry path.',
  },

  // ---------- P7 ----------
  databricksFree: {
    id: 'databricks-free-edition',
    title: 'Databricks Free Edition',
    provider: 'Databricks',
    url: 'https://www.databricks.com/learn/free-edition',
    format: 'interactive',
    hours: 1,
    interactivity: 3,
    visual: 2,
    handsOn: 5,
    popularity: 4,
    pitch: 'Free workspace to run the agent against real Spark / SQL.',
  },
  makeReadme: {
    id: 'make-a-readme',
    title: 'Make a README',
    provider: 'makeareadme.com',
    url: 'https://www.makeareadme.com',
    format: 'article',
    hours: 0.3,
    interactivity: 2,
    visual: 3,
    handsOn: 3,
    popularity: 4,
    pitch: 'What a great README contains, with a live template.',
  },
  mermaid: {
    id: 'mermaid-docs',
    title: 'Mermaid – diagrams as code',
    provider: 'Mermaid',
    url: 'https://mermaid.js.org',
    format: 'docs',
    hours: 0.5,
    interactivity: 4,
    visual: 4,
    handsOn: 4,
    popularity: 5,
    pitch: 'Architecture diagrams that render natively on GitHub.',
  },
  demoVideo: {
    id: 'demo-video-tips',
    title: 'How to record a software demo (video picks)',
    provider: 'YouTube',
    url: ytSearch('how to record a software demo video tips'),
    format: 'video',
    hours: 0.5,
    interactivity: 1,
    visual: 3,
    handsOn: 2,
    popularity: 3,
    pitch: 'Short, punchy, problem → live run → result.',
  },

  // ---------- P8 ----------
  huyenPlatform: {
    id: 'huyen-genai-platform',
    title: 'Building A Generative AI Platform',
    provider: 'Chip Huyen',
    url: 'https://huyenchip.com/2024/07/25/genai-platform.html',
    format: 'article',
    hours: 1.5,
    interactivity: 1,
    visual: 4,
    handsOn: 1,
    popularity: 5,
    pitch: 'The reference architecture diagram every interviewer knows.',
  },
  aieBook: {
    id: 'chip-aie-book-repo',
    title: 'AI Engineering – book resources',
    provider: 'Chip Huyen · GitHub',
    url: 'https://github.com/chiphuyen/aie-book',
    format: 'article',
    hours: 2,
    interactivity: 2,
    visual: 2,
    handsOn: 2,
    popularity: 5,
    pitch: 'Free companion resources, case studies and prompt examples.',
  },
  sysDesignVideo: {
    id: 'llm-system-design-video',
    title: 'LLM system design interviews (video picks)',
    provider: 'YouTube',
    url: ytSearch('LLM system design interview GenAI'),
    format: 'video',
    hours: 3,
    interactivity: 1,
    visual: 3,
    handsOn: 1,
    popularity: 4,
    pitch: 'Watch 3–4 mock designs, then whiteboard your own.',
  },
  dlaiFinetune: {
    id: 'dlai-finetuning-llms',
    title: 'Finetuning Large Language Models',
    provider: 'DeepLearning.AI × Lamini',
    url: dlai('finetuning-large-language-models'),
    format: 'course',
    hours: 1,
    interactivity: 4,
    visual: 3,
    handsOn: 4,
    popularity: 5,
    pitch: 'When and how to fine-tune, with runnable notebooks.',
  },
  unsloth: {
    id: 'unsloth-docs',
    title: 'Unsloth – fine-tune on free Colab GPUs',
    provider: 'Unsloth',
    url: 'https://docs.unsloth.ai',
    format: 'notebook',
    hours: 3,
    interactivity: 4,
    visual: 2,
    handsOn: 5,
    popularity: 5,
    pitch: 'Free notebooks: LoRA fine-tune Llama / Qwen 2× faster.',
  },
  msAppliedSkills: {
    id: 'ms-applied-skills',
    title: 'Microsoft Applied Skills (free credentials)',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/credentials/browse/?credential_types=applied%20skills',
    format: 'interactive',
    hours: 6,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    certificate: true,
    pitch: 'Free, lab-based Azure AI credentials. Great résumé signal.',
  },
  interviewVideo: {
    id: 'ai-engineer-interview-video',
    title: 'AI engineer interview questions (video picks)',
    provider: 'YouTube',
    url: ytSearch('AI engineer interview questions GenAI RAG agents'),
    format: 'video',
    hours: 2,
    interactivity: 1,
    visual: 3,
    handsOn: 1,
    popularity: 4,
    pitch: 'Collect questions into the Career flashcards.',
  },
  techInterviewHandbook: {
    id: 'tech-interview-handbook-behavioral',
    title: 'Behavioral interview guide',
    provider: 'Tech Interview Handbook',
    url: 'https://www.techinterviewhandbook.org/behavioral-interview/',
    format: 'article',
    hours: 1,
    interactivity: 2,
    visual: 3,
    handsOn: 2,
    popularity: 5,
    pitch: 'STAR stories and common questions, free and concise.',
  },
} satisfies Record<string, C>;
