import type { Course } from './schema';

type VideoInput = Omit<Course, 'url' | 'format' | 'interactivity'> & {
  youtubeId: string;
  interactivity?: number;
};

// All YouTube IDs below were verified against YouTube oEmbed (title + channel).
const v = (o: VideoInput): Course => ({
  format: 'video',
  interactivity: 1,
  url: `https://www.youtube.com/watch?v=${o.youtubeId}`,
  ...o,
});

const playlist = (listId: string) => `https://www.youtube.com/playlist?list=${listId}`;

export const more = {
  // ---------- P0 ----------
  ngOpportunities: v({
    id: 'ng-opportunities-in-ai',
    youtubeId: '5p248yoa3oE',
    title: 'Andrew Ng: Opportunities in AI',
    provider: 'Stanford Online',
    hours: 0.6,
    visual: 3,
    handsOn: 1,
    popularity: 5,
    pitch: 'Where the value in AI is — and why builders on top of LLMs win.',
  }),

  // ---------- P1 · Python core ----------
  pierianBootcamp: {
    id: 'pierian-python-bootcamp',
    title: 'Complete Python Bootcamp: From Zero to Hero',
    provider: 'Pierian Training · Udemy',
    url: 'https://www.udemy.com/course/complete-python-bootcamp/',
    format: 'course',
    hours: 22,
    interactivity: 3,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    certificate: true,
    paid: true,
    pitch: 'Your chosen bootcamp. You know Python — cherry-pick OOP, decorators, generators, errors.',
    lessons: [
      'Objects & data structures',
      'Comparison operators & statements',
      'Methods & functions',
      'Milestone project 1',
      'Object-oriented programming',
      'Modules & packages',
      'Errors & exception handling',
      'Milestone project 2',
      'Decorators',
      'Generators',
      'Advanced Python modules',
      'Working with CSV / PDF files',
      'Advanced objects & data structures',
      'Final capstone project',
    ],
  },
  pierianRepo: {
    id: 'pierian-python-notebooks',
    title: 'Complete Python 3 Bootcamp – notebooks',
    provider: 'Pierian Data · GitHub',
    url: 'https://github.com/Pierian-Data/Complete-Python-3-Bootcamp',
    format: 'notebook',
    hours: 10,
    interactivity: 3,
    visual: 2,
    handsOn: 5,
    popularity: 5,
    pitch: 'Free companion Jupyter notebooks + exercises for the bootcamp.',
  },
  cs50pVideo: v({
    id: 'cs50p-full-course',
    youtubeId: 'nLRL_NcnK-4',
    title: "Harvard CS50's Introduction to Programming with Python",
    provider: 'freeCodeCamp · Harvard',
    hours: 16,
    visual: 4,
    handsOn: 5,
    popularity: 5,
    pitch: "David Malan's legendary teaching. Watch the lectures you need.",
    lessons: [
      'Functions & variables',
      'Conditionals',
      'Loops',
      'Exceptions',
      'Libraries',
      'Unit tests',
      'File I/O',
      'Regular expressions',
      'Object-oriented programming',
      'Et cetera (type hints, generators, …)',
    ],
  }),
  cs50pSite: {
    id: 'cs50p-problem-sets',
    title: 'CS50P problem sets (auto-graded) + certificate',
    provider: 'Harvard CS50',
    url: 'https://cs50.harvard.edu/python/',
    format: 'interactive',
    hours: 20,
    interactivity: 5,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    certificate: true,
    pitch: 'Auto-graded exercises + free certificate. Do the OOP and tests sets.',
  },
  fccIntermediatePython: v({
    id: 'fcc-intermediate-python',
    youtubeId: 'HGOBQPFzWKo',
    title: 'Intermediate Python Programming Course',
    provider: 'freeCodeCamp',
    hours: 6,
    visual: 3,
    handsOn: 4,
    popularity: 5,
    pitch: 'Collections, itertools, lambdas, decorators, generators, threading.',
  }),
  moshPython: v({
    id: 'mosh-python-full',
    youtubeId: '_uQrJ0TkZlc',
    title: 'Python Full Course for Beginners',
    provider: 'Programming with Mosh',
    hours: 6,
    visual: 4,
    handsOn: 4,
    popularity: 5,
    pitch: 'Crisp, well-paced refresher from a top-rated instructor.',
  }),
  fccLearnPython: v({
    id: 'fcc-learn-python',
    youtubeId: 'rfscVS0vtbw',
    title: 'Learn Python – Full Course for Beginners',
    provider: 'freeCodeCamp',
    hours: 4.5,
    visual: 3,
    handsOn: 4,
    popularity: 5,
    pitch: "One of YouTube's most-watched Python courses. Skim at 1.5×.",
  }),
  py4e: v({
    id: 'py4e-full-course',
    youtubeId: '8DvywoWv6fI',
    title: 'Python for Everybody – Full University Course',
    provider: 'freeCodeCamp · Dr. Chuck',
    hours: 14,
    visual: 3,
    handsOn: 3,
    popularity: 5,
    pitch: 'Beloved university course; strong on files, data and web APIs.',
  }),
  automateBoring: {
    id: 'automate-the-boring-stuff',
    title: 'Automate the Boring Stuff with Python (free book)',
    provider: 'Al Sweigart',
    url: 'https://automatetheboringstuff.com',
    format: 'article',
    hours: 10,
    interactivity: 2,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Files, Excel, CSV, web scraping — practical automation you will reuse.',
  },
  coreySchafer: {
    id: 'corey-schafer-channel',
    title: 'Corey Schafer – Python tutorials',
    provider: 'Corey Schafer · YouTube',
    url: 'https://www.youtube.com/@coreyms',
    format: 'video',
    hours: 4,
    interactivity: 1,
    visual: 4,
    handsOn: 4,
    popularity: 5,
    pitch: 'Community favourite: OOP, decorators, generators, logging deep dives.',
  },
  realPythonTypes: {
    id: 'realpython-type-checking',
    title: 'Python Type Checking (Guide)',
    provider: 'Real Python',
    url: 'https://realpython.com/python-type-checking/',
    format: 'article',
    hours: 1.5,
    interactivity: 2,
    visual: 3,
    handsOn: 4,
    popularity: 4,
    pitch: 'Type hints the way LangChain, FastAPI and Pydantic expect them.',
  },

  // ---------- P1 · modern / APIs / FastAPI ----------
  pixegamiPydantic: v({
    id: 'pixegami-pydantic',
    youtubeId: 'XIdQ6gO3Anc',
    title: "Pydantic Tutorial • Solving Python's Biggest Problem",
    provider: 'pixegami',
    hours: 0.2,
    visual: 4,
    handsOn: 3,
    popularity: 4,
    pitch: 'Short, visual intro to why typed models matter.',
  }),
  pixegamiPytest: v({
    id: 'pixegami-pytest',
    youtubeId: 'YbpKMIUjvK8',
    title: 'How To Write Unit Tests in Python • Pytest Tutorial',
    provider: 'pixegami',
    hours: 0.6,
    visual: 4,
    handsOn: 4,
    popularity: 4,
    pitch: 'Fixtures, parametrize, assertions — in one tidy walkthrough.',
  }),
  coreyUnittest: v({
    id: 'corey-unittest',
    youtubeId: '6tNS--WetLI',
    title: 'Unit Testing Your Code with the unittest Module',
    provider: 'Corey Schafer',
    hours: 0.6,
    visual: 3,
    handsOn: 4,
    popularity: 5,
    pitch: 'Classic, clear explanation of unit-testing fundamentals.',
  }),
  keithPandas: v({
    id: 'keith-galli-pandas',
    youtubeId: 'vmEHCJofslg',
    title: 'Complete Python Pandas Data Science Tutorial',
    provider: 'Keith Galli',
    hours: 1,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Filtering, groupby, CSV/Excel — the SQL you know, in pandas.',
  }),
  arjanAsyncio: v({
    id: 'arjancodes-asyncio',
    youtubeId: 'GpqAQxH1Afc',
    title: 'Next-Level Concurrent Programming In Python With Asyncio',
    provider: 'ArjanCodes',
    hours: 0.35,
    visual: 4,
    handsOn: 4,
    popularity: 4,
    pitch: 'Real-world asyncio patterns: gather, tasks, concurrency limits.',
  }),
  mcodingAsync: v({
    id: 'mcoding-async',
    youtubeId: 'ftmdDlwMwwQ',
    title: 'Intro to async Python | Writing a Web Crawler',
    provider: 'mCoding',
    hours: 0.25,
    visual: 4,
    handsOn: 4,
    popularity: 4,
    pitch: 'Build a concurrent crawler — same shape as batch LLM calls.',
  }),
  fccFastapiBeginners: v({
    id: 'fcc-fastapi-beginners',
    youtubeId: 'tLKKmouUams',
    title: 'FastAPI Course for Beginners',
    provider: 'freeCodeCamp',
    hours: 1,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'One-hour build-along. The fastest way to feel productive.',
  }),

  // ---------- P2 ----------
  statquestIntroMl: v({
    id: 'statquest-intro-ml',
    youtubeId: 'Gv9_4yMHFhI',
    title: 'A Gentle Introduction to Machine Learning',
    provider: 'StatQuest',
    hours: 0.2,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'The kindest 12-minute ML intro on the internet.',
  }),
  statquestBiasVariance: v({
    id: 'statquest-bias-variance',
    youtubeId: 'EuBBz3bI-aA',
    title: 'Machine Learning Fundamentals: Bias and Variance',
    provider: 'StatQuest',
    hours: 0.1,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'Overfitting vs underfitting, drawn out step by step.',
  }),
  fccMlEverybody: v({
    id: 'fcc-ml-for-everybody',
    youtubeId: 'i_LwzRVP7bg',
    title: 'Machine Learning for Everybody – Full Course',
    provider: 'freeCodeCamp · Kylie Ying',
    hours: 3.9,
    visual: 4,
    handsOn: 4,
    popularity: 5,
    pitch: 'Intuition first, then code in Colab. Highly rated by learners.',
  }),
  ngMlSpecialization: {
    id: 'ng-ml-specialization',
    title: 'Machine Learning Specialization (Andrew Ng)',
    provider: 'DeepLearning.AI · Coursera (audit)',
    url: 'https://www.coursera.org/specializations/machine-learning-introduction',
    format: 'course',
    hours: 30,
    interactivity: 4,
    visual: 4,
    handsOn: 4,
    popularity: 5,
    pitch: 'The most-enrolled ML course ever. Audit free; watch Course 1 selectively.',
  },
  backprop3b1b: v({
    id: '3b1b-backprop',
    youtubeId: 'Ilg3gGewQ5U',
    title: 'Backpropagation, intuitively',
    provider: '3Blue1Brown',
    hours: 0.2,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'Chapter 3: how the network figures out what to change.',
  }),
  backpropCalc3b1b: v({
    id: '3b1b-backprop-calculus',
    youtubeId: 'tIeHLnjs5U8',
    title: 'Backpropagation calculus',
    provider: '3Blue1Brown',
    hours: 0.2,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'Chapter 4 (optional): the maths, beautifully animated.',
  }),
  statquestNn: v({
    id: 'statquest-nn-main-ideas',
    youtubeId: 'CqOfi41LfDw',
    title: 'The Essential Main Ideas of Neural Networks',
    provider: 'StatQuest',
    hours: 0.3,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'Neural nets as bendy squiggles. It finally clicks.',
  }),
  fastaiLesson1: v({
    id: 'fastai-lesson-1',
    youtubeId: '8SF_h3xF3cE',
    title: 'Practical Deep Learning for Coders: Lesson 1',
    provider: 'Jeremy Howard · fast.ai',
    hours: 1.5,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Train an image classifier in minutes. Top-down learning.',
  }),
  nnSeries3b1b: {
    id: '3b1b-nn-playlist',
    title: 'Neural networks – full series (playlist)',
    provider: '3Blue1Brown',
    url: playlist('PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi'),
    format: 'video',
    hours: 3,
    interactivity: 1,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'All chapters: neurons → backprop → transformers → attention.',
  },
  zeroToHero: {
    id: 'karpathy-zero-to-hero',
    title: 'Neural Networks: Zero to Hero (playlist)',
    provider: 'Andrej Karpathy',
    url: playlist('PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ'),
    format: 'video',
    hours: 15,
    interactivity: 2,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Deep track: micrograd → makemore → GPT. For weekends.',
  },
  statquestWord2vec: v({
    id: 'statquest-word2vec',
    youtubeId: 'viZrOnJclY0',
    title: 'Word Embedding and Word2Vec, Clearly Explained',
    provider: 'StatQuest',
    hours: 0.3,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'How words become vectors — the foundation of RAG.',
  }),

  // ---------- P3 ----------
  ibmHowLlmsWork: v({
    id: 'ibm-how-llms-work',
    youtubeId: '5sLYAQS9sWQ',
    title: 'How Large Language Models Work',
    provider: 'IBM Technology',
    hours: 0.1,
    visual: 4,
    handsOn: 1,
    popularity: 5,
    pitch: 'Lightboard explainer. Perfect 6-minute warm-up.',
  }),
  statquestTransformer: v({
    id: 'statquest-transformer',
    youtubeId: 'zxQyTK8quyY',
    title: "Transformer Neural Networks, ChatGPT's foundation",
    provider: 'StatQuest',
    hours: 0.6,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'Every piece of the transformer, clearly drawn.',
  }),
  reproduceGpt2: v({
    id: 'karpathy-reproduce-gpt2',
    youtubeId: 'l8pRSuU81PU',
    title: "Let's reproduce GPT-2 (124M)",
    provider: 'Andrej Karpathy',
    interactivity: 2,
    hours: 4,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Stretch goal: train a real GPT-2 end to end.',
  }),
  mlabonneCourse: {
    id: 'mlabonne-llm-course',
    title: 'LLM Course (roadmaps + Colab notebooks)',
    provider: 'Maxime Labonne · GitHub',
    url: 'https://github.com/mlabonne/llm-course',
    format: 'notebook',
    hours: 10,
    interactivity: 3,
    visual: 4,
    handsOn: 5,
    popularity: 5,
    pitch: "One of GitHub's most-starred LLM curricula, with runnable notebooks.",
  },
  anthropicPromptDeepDive: v({
    id: 'anthropic-prompt-deep-dive',
    youtubeId: 'T9aRN5JkmL8',
    title: 'AI prompt engineering: A deep dive',
    provider: 'Anthropic',
    hours: 1.3,
    visual: 3,
    handsOn: 2,
    popularity: 4,
    pitch: "Anthropic's prompt engineers discuss what actually works.",
  }),
  fccPromptEng: v({
    id: 'fcc-prompt-engineering',
    youtubeId: '_ZvnD73m40o',
    title: 'Prompt Engineering Tutorial – Master ChatGPT and LLM Responses',
    provider: 'freeCodeCamp',
    hours: 0.7,
    visual: 3,
    handsOn: 3,
    popularity: 4,
    pitch: 'Techniques with examples: zero/few-shot, CoT, personas.',
  }),

  // ---------- P4 ----------
  fireshipVectorDb: v({
    id: 'fireship-vector-databases',
    youtubeId: 'klTvEwg3oJ4',
    title: 'Vector databases are so hot right now. WTF are they?',
    provider: 'Fireship',
    hours: 0.1,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'Fast, funny, clear. The perfect 3-minute primer.',
  }),
  fccVectorEmbeddings: v({
    id: 'fcc-vector-embeddings',
    youtubeId: 'yfHHvmaMkcA',
    title: 'Vector Embeddings Tutorial – Code Your Own AI Assistant',
    provider: 'freeCodeCamp',
    hours: 0.6,
    visual: 3,
    handsOn: 4,
    popularity: 4,
    pitch: 'Embeddings → vector search → assistant, coded step by step.',
  }),
  ibmRag: v({
    id: 'ibm-what-is-rag',
    youtubeId: 'T-D1OfcDW1M',
    title: 'What is Retrieval-Augmented Generation (RAG)?',
    provider: 'IBM Technology',
    hours: 0.1,
    visual: 4,
    handsOn: 1,
    popularity: 5,
    pitch: 'The clearest 6-minute RAG explanation. Start here.',
  }),
  pixegamiRag: v({
    id: 'pixegami-rag-langchain',
    youtubeId: 'tcqEUSNCn8I',
    title: 'RAG + Langchain Python Project: Easy AI/Chat For Your Docs',
    provider: 'pixegami',
    hours: 0.3,
    visual: 4,
    handsOn: 5,
    popularity: 5,
    pitch: 'Much-loved compact build: docs → Chroma → answers with sources.',
  }),
  brandonLangchain: v({
    id: 'langchain-master-class',
    youtubeId: 'yF9kGESAi3M',
    title: 'LangChain Master Class For Beginners',
    provider: 'aiwithbrandon',
    hours: 3.5,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    pitch: '20+ examples: chat models, prompts, chains, RAG, agents.',
  }),
  llmZoomcamp: {
    id: 'llm-zoomcamp',
    title: 'LLM Zoomcamp (free course)',
    provider: 'DataTalksClub · GitHub',
    url: 'https://github.com/DataTalksClub/llm-zoomcamp',
    format: 'course',
    hours: 30,
    interactivity: 4,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    certificate: true,
    pitch: 'Community-loved: RAG, vector search, evaluation, monitoring + homework.',
  },
  kamradtSplitting: v({
    id: 'kamradt-text-splitting',
    youtubeId: '8OJC21T2SL4',
    title: 'The 5 Levels Of Text Splitting For Retrieval',
    provider: 'Greg Kamradt',
    hours: 1.2,
    visual: 4,
    handsOn: 4,
    popularity: 5,
    pitch: 'The definitive chunking guide, from naive to semantic.',
  }),
  jerryLiuRag: v({
    id: 'jerry-liu-production-rag',
    youtubeId: 'TRjq7t2Ms5I',
    title: 'Building Production-Ready RAG Applications',
    provider: 'Jerry Liu · AI Engineer',
    hours: 0.3,
    visual: 3,
    handsOn: 2,
    popularity: 4,
    pitch: "LlamaIndex founder on what breaks in real RAG and how to fix it.",
  }),

  // ---------- P5 ----------
  ibmAgents: v({
    id: 'ibm-what-are-ai-agents',
    youtubeId: 'F8NKVhkZZWI',
    title: 'What are AI Agents?',
    provider: 'IBM Technology',
    hours: 0.2,
    visual: 4,
    handsOn: 1,
    popularity: 5,
    pitch: 'Compound AI systems → agents, explained on a lightboard.',
  }),
  barryZhangAgents: v({
    id: 'anthropic-effective-agents-talk',
    youtubeId: 'D7_ipDqhtwk',
    title: 'How We Build Effective Agents',
    provider: 'Barry Zhang (Anthropic) · AI Engineer',
    hours: 0.25,
    visual: 3,
    handsOn: 1,
    popularity: 5,
    pitch: 'The talk version of "Building effective agents". Must-watch.',
  }),
  ebbelaarAgents: v({
    id: 'ebbelaar-agents-pure-python',
    youtubeId: 'bZzyPscbtI8',
    title: 'Building AI Agents in Pure Python – Beginner Course',
    provider: 'Dave Ebbelaar',
    hours: 1,
    visual: 3,
    handsOn: 5,
    popularity: 4,
    pitch: 'No frameworks: tools, structured output, routing — from scratch.',
  }),
  harrisonAgents: v({
    id: 'harrison-chase-agents',
    youtubeId: 'pBBe1pk8hf4',
    title: "What's next for AI agents ft. LangChain's Harrison Chase",
    provider: 'Sequoia Capital',
    hours: 0.3,
    visual: 3,
    handsOn: 1,
    popularity: 4,
    pitch: 'Planning, UX and memory — where agents are heading.',
  }),
  fccLanggraph: v({
    id: 'fcc-langgraph-course',
    youtubeId: 'jGg_1h0qzaM',
    title: 'LangGraph Complete Course for Beginners',
    provider: 'freeCodeCamp',
    hours: 3,
    visual: 3,
    handsOn: 5,
    popularity: 5,
    pitch: 'Graphs, state, tools, RAG agent — full build-along.',
  }),
  langgraphMultiAgent: v({
    id: 'langgraph-multi-agent-workflows',
    youtubeId: 'hvAPnpSfSGo',
    title: 'LangGraph: Multi-Agent Workflows',
    provider: 'LangChain',
    hours: 0.3,
    visual: 3,
    handsOn: 4,
    popularity: 4,
    pitch: 'Supervisor, collaboration and hierarchical teams, from the source.',
  }),
  maheshMcp: v({
    id: 'anthropic-mcp-workshop',
    youtubeId: 'kQmXtrmQ5Zg',
    title: 'Building Agents with Model Context Protocol – Full Workshop',
    provider: 'Mahesh Murag (Anthropic) · AI Engineer',
    hours: 1.8,
    visual: 3,
    handsOn: 4,
    popularity: 5,
    pitch: 'MCP explained by the Anthropic team that built it.',
  }),

  // ---------- P6 ----------
  lennyEvals: v({
    id: 'lenny-evals-hamel-shreya',
    youtubeId: 'BsWxPI9UM4c',
    title: 'Why AI evals are the hottest new skill',
    provider: "Lenny's Podcast · Hamel & Shreya",
    hours: 1.7,
    visual: 2,
    handsOn: 2,
    popularity: 4,
    pitch: 'The evals workflow top AI teams use. Your QA superpower, validated.',
  }),
  ibmPromptInjection: v({
    id: 'ibm-prompt-injection',
    youtubeId: 'jrHRe9lSqqA',
    title: 'What Is a Prompt Injection Attack?',
    provider: 'IBM Technology',
    hours: 0.2,
    visual: 4,
    handsOn: 1,
    popularity: 4,
    pitch: 'How injections work and the layered defences against them.',
  }),
  fireshipDocker: v({
    id: 'fireship-docker-100s',
    youtubeId: 'Gjnup-PuquQ',
    title: 'Docker in 100 Seconds',
    provider: 'Fireship',
    hours: 0.05,
    visual: 5,
    handsOn: 1,
    popularity: 5,
    pitch: 'The whole idea in under two minutes.',
  }),
  fireshipDockerConcepts: v({
    id: 'fireship-docker-concepts',
    youtubeId: 'rIrNIzy6U_g',
    title: '100+ Docker Concepts you Need to Know',
    provider: 'Fireship',
    hours: 0.3,
    visual: 5,
    handsOn: 2,
    popularity: 5,
    pitch: 'Dense, visual tour of everything Docker.',
  }),
  fccDocker: v({
    id: 'fcc-docker-course',
    youtubeId: 'fqMOX6JJhGo',
    title: 'Docker Tutorial for Beginners – Full DevOps Course',
    provider: 'freeCodeCamp',
    hours: 2,
    visual: 3,
    handsOn: 4,
    popularity: 5,
    pitch: 'Classic hands-on course: images, compose, networking.',
  }),
  az900: v({
    id: 'fcc-az-900',
    youtubeId: 'NKEFWyqJ5XA',
    title: 'Microsoft Azure Fundamentals (AZ-900) Full Course',
    provider: 'freeCodeCamp',
    hours: 3.5,
    visual: 3,
    handsOn: 2,
    popularity: 5,
    pitch: 'Fast Azure refresher before AI Foundry and Container Apps.',
  }),

  // ---------- P8 ----------
  umarLora: v({
    id: 'umar-jamil-lora',
    youtubeId: 'PXWYUTMt-AU',
    title: 'LoRA explained visually + PyTorch code from scratch',
    provider: 'Umar Jamil',
    hours: 0.45,
    visual: 5,
    handsOn: 4,
    popularity: 4,
    pitch: 'Why low-rank adapters work, drawn and coded.',
  }),
  shawFinetune: v({
    id: 'shaw-talebi-finetuning',
    youtubeId: 'eC6Hd1hFvos',
    title: 'Fine-tuning Large Language Models (w/ Example Code)',
    provider: 'Shaw Talebi',
    hours: 0.5,
    visual: 4,
    handsOn: 4,
    popularity: 4,
    pitch: 'When to fine-tune, and a full LoRA example in Python.',
  }),
} satisfies Record<string, Course>;
