import { courses as c } from './courses';
import { more as m } from './moreCourses';
import type { Phase } from './schema';

export const phases: Phase[] = [
  {
    id: 'p0',
    order: 0,
    title: 'Launchpad',
    icon: 'Rocket',
    hue: 'sky',
    goal: 'Know the target role and set up a friction-free dev environment.',
    modules: [
      {
        id: 'p0-role',
        title: 'What an AI Engineer does',
        kind: 'learn',
        icon: 'Compass',
        studyDays: 1,
        tagline: 'Build products on top of LLMs — not train them from scratch.',
        flow: ['Business problem', 'Data', 'LLM + tools', 'Evals', 'Deploy', 'Users'],
        cards: [
          { icon: 'Bot', title: 'Builds with models', text: 'Uses pre-trained LLMs via APIs, adds data, tools and guardrails.' },
          { icon: 'ShieldCheck', title: 'Quality is the job', text: 'Evals, testing and reliability decide if AI ships. Your home turf.' },
          { icon: 'Rocket', title: 'Ships end-to-end', text: 'API, UI, cloud, monitoring. One person, one working product.' },
        ],
        bridge: 'You already validate pipelines end-to-end. AI engineering = pipelines where one step is an LLM.',
        build: "Write your 1-line pitch: 'Data quality engineer who builds reliable AI systems.' Save it in Notes.",
        courses: [c.baraaRoadmap, c.babbarRoadmap, c.karpathySoftware, m.ngOpportunities, c.roadmapSh],
        quiz: [
          {
            q: 'Main difference between an AI Engineer and an ML Engineer?',
            options: [
              'AI Engineers mainly train models from scratch',
              'AI Engineers build products on pre-trained models',
              'There is no difference',
              'AI Engineers only write prompts',
            ],
            answer: 1,
          },
          {
            q: 'Which of your existing skills transfers most directly?',
            options: ['UI animation', 'Data validation & testing', 'Network cabling', 'Graphic design'],
            answer: 1,
          },
        ],
      },
      {
        id: 'p0-setup',
        title: 'Dev setup & free AI keys',
        kind: 'learn',
        icon: 'Terminal',
        studyDays: 1,
        tagline: 'One-time setup so every day after is pure learning.',
        flow: ['VS Code', 'uv + Python 3.12', 'Git + GitHub', 'Free LLM keys', 'Ollama local'],
        cards: [
          { icon: 'Code2', title: 'Editor + Copilot', text: 'VS Code with Python, Jupyter and GitHub Copilot free tier.' },
          { icon: 'Zap', title: 'Free LLM access', text: 'Gemini free tier, GitHub Models, and Ollama running locally.' },
          { icon: 'Lock', title: 'Secrets hygiene', text: 'Keys live in .env, never in Git. Same rule as prod DB passwords.' },
        ],
        bridge: 'Same discipline as ADF linked services: connections, secrets, environments.',
        build: "Create repo 'ai-engineer-journey' and run a 'hello LLM' script against Gemini and Ollama.",
        courses: [c.uv, c.ollama, c.aiStudio, c.githubModels],
        quiz: [
          {
            q: 'Where should API keys live?',
            options: ['In source code', 'In a .env file excluded by .gitignore', 'In the README', 'In a commit message'],
            answer: 1,
          },
          {
            q: 'What does Ollama give you?',
            options: ['A cloud GPU cluster', 'Local LLMs on your machine', 'A vector database', 'A CI pipeline'],
            answer: 1,
          },
        ],
      },
    ],
  },
  {
    id: 'p1',
    order: 1,
    title: 'Python for AI Eng',
    icon: 'Code2',
    hue: 'emerald',
    goal: 'Production-style Python: typed, tested, API-ready.',
    modules: [
      {
        id: 'p1-core',
        title: 'Python core refresh (bootcamp track)',
        kind: 'learn',
        icon: 'Code2',
        studyDays: 2,
        tagline: 'Sharpen OOP, comprehensions, decorators, generators and error handling.',
        flow: ['Data structures', 'Functions', 'OOP', 'Decorators', 'Generators', 'Errors'],
        cards: [
          { icon: 'Boxes', title: 'Data structures', text: 'Lists, dicts, sets, comprehensions — the daily tools of LLM apps.' },
          { icon: 'Layers', title: 'OOP & dataclasses', text: 'Classes model agents, tools and pipelines cleanly.' },
          { icon: 'Repeat', title: 'Generators & decorators', text: 'Token streaming and @retry wrappers use exactly these.' },
        ],
        bridge: 'Classes are reusable test frameworks; decorators are pre/post-validation hooks.',
        build: 'Refactor an old validation script into a class with a @retry decorator and a row-streaming generator.',
        tip: 'Pierian bootcamp is ~22 h: do OOP, errors, decorators and generators now; the rest alongside later phases.',
        courses: [
          m.pierianBootcamp,
          m.pierianRepo,
          m.cs50pVideo,
          m.cs50pSite,
          m.fccIntermediatePython,
          m.moshPython,
          m.coreySchafer,
          m.automateBoring,
          m.py4e,
          m.fccLearnPython,
          m.realPythonTypes,
        ],
        quiz: [
          {
            q: 'Why are generators useful in LLM apps?',
            options: ['They stream items lazily, e.g. tokens or rows', 'They compile code', 'They encrypt data', 'They replace classes'],
            answer: 0,
          },
          {
            q: 'A decorator is…',
            options: ['A function that wraps another to add behaviour', 'A CSS style', 'A database index', 'A comment'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p1-modern',
        title: 'Modern Python: Pydantic & pytest',
        kind: 'learn',
        icon: 'Code2',
        studyDays: 2,
        tagline: 'Typed data models are the contracts of AI apps.',
        flow: ['Raw JSON', 'Pydantic model', 'Validation', 'Typed object', 'pytest'],
        cards: [
          { icon: 'ShieldCheck', title: 'Pydantic = schema checks', text: 'Like target-table constraints, but for Python objects and LLM outputs.' },
          { icon: 'FlaskConical', title: 'pytest', text: 'Your test-case mindset as code: fixtures, parametrize, asserts.' },
          { icon: 'Layers', title: 'Type hints', text: 'Editors catch bugs before runtime. LLM frameworks rely on them.' },
        ],
        bridge: 'Pydantic validation ≈ the data-type and constraint checks you have run for 10 years.',
        build: 'Model one STTM row (source col, target col, rule) as a Pydantic class and test it with pytest.',
        courses: [c.pydantic, c.pytest, m.pixegamiPydantic, m.pixegamiPytest, m.coreyUnittest, c.kagglePandas, m.keithPandas],
        quiz: [
          {
            q: 'Pydantic mainly helps you…',
            options: ['Plot charts', 'Validate and parse data into typed objects', 'Train neural nets', 'Host websites'],
            answer: 1,
          },
          {
            q: '@pytest.mark.parametrize is most like…',
            options: ['One test case run with many data rows', 'Deleting tests', 'Compiling Python', 'Formatting code'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p1-apis',
        title: 'HTTP APIs, JSON & async',
        kind: 'learn',
        icon: 'Globe',
        studyDays: 2,
        tagline: 'Every LLM is an HTTP API. Master calling them well.',
        flow: ['Request', 'Retry + backoff', 'Rate limit', 'Parse JSON', 'Async fan-out'],
        cards: [
          { icon: 'Globe', title: 'httpx / requests', text: 'Call REST APIs; handle status codes, timeouts and auth headers.' },
          { icon: 'Repeat', title: 'Retries & backoff', text: 'LLM APIs throttle. Exponential backoff is mandatory.' },
          { icon: 'Zap', title: 'async/await', text: 'Send 50 prompts in parallel instead of one by one.' },
        ],
        bridge: 'Like ADF Web activities + retry policies, but in code you fully control.',
        build: 'Write an async script that sends 10 prompts to Gemini concurrently with retry + timeout.',
        courses: [c.realPythonAsync, c.httpx, m.arjanAsyncio, m.mcodingAsync],
        quiz: [
          {
            q: 'Best way to handle HTTP 429 from an LLM API?',
            options: ['Crash', 'Retry with exponential backoff', 'Ignore it', 'Switch to FTP'],
            answer: 1,
          },
          {
            q: 'async/await in Python is best for…',
            options: ['CPU-heavy maths', 'Waiting on many I/O calls concurrently', 'Styling UIs', 'Compiling C'],
            answer: 1,
          },
        ],
      },
      {
        id: 'p1-fastapi',
        title: 'FastAPI: ship an API',
        kind: 'learn',
        icon: 'Server',
        studyDays: 2,
        tagline: 'Wrap any AI logic in a clean, documented REST API.',
        flow: ['Pydantic request', 'FastAPI route', 'Your logic', 'Pydantic response', 'Swagger UI'],
        cards: [
          { icon: 'Server', title: 'Auto docs', text: 'Interactive Swagger UI generated for free at /docs.' },
          { icon: 'ShieldCheck', title: 'Validation built-in', text: 'Bad requests are rejected by Pydantic before your code runs.' },
          { icon: 'Zap', title: 'Async ready', text: 'Native async routes for LLM calls and streaming.' },
        ],
        bridge: 'Your DQ automation tools become services other teams can call.',
        build: 'Expose POST /validate that accepts a table profile and returns rule violations.',
        courses: [c.fastapi, m.fccFastapiBeginners, c.fccFastapi],
        quiz: [
          {
            q: 'Where does FastAPI serve interactive docs by default?',
            options: ['/swagger.exe', '/docs', '/admin', '/api.txt'],
            answer: 1,
          },
          {
            q: 'FastAPI validates request bodies using…',
            options: ['Regex only', 'Pydantic models', 'XML schemas', 'Nothing'],
            answer: 1,
          },
        ],
      },
    ],
  },
  {
    id: 'p2',
    order: 2,
    title: 'ML & DL Intuition',
    icon: 'Brain',
    hue: 'violet',
    goal: 'See how models learn — visually, with minimal maths.',
    modules: [
      {
        id: 'p2-ml',
        title: 'Machine learning in pictures',
        kind: 'learn',
        icon: 'Telescope',
        studyDays: 2,
        tagline: 'Models learn patterns from examples instead of hand-written rules.',
        flow: ['Data', 'Features', 'Train', 'Validate', 'Predict'],
        cards: [
          { icon: 'Database', title: 'Train / test split', text: 'Never grade a model on data it studied. Like UAT vs dev data.' },
          { icon: 'Scale', title: 'Overfitting', text: 'Memorising noise: great on training data, bad in production.' },
          { icon: 'Gauge', title: 'Metrics', text: 'Precision, recall, F1 — defect-leakage metrics in disguise.' },
        ],
        bridge: 'Precision / recall = false alarms vs missed defects in your validation reports.',
        build: "Kaggle notebook: train a model that flags 'bad' rows in a data-quality dataset.",
        courses: [c.googleMlcc, c.kaggleIntroMl, m.statquestIntroMl, m.statquestBiasVariance, m.fccMlEverybody, c.r2d3, c.statquest, m.ngMlSpecialization],
        quiz: [
          {
            q: '99% on training data, 60% on test data. That is…',
            options: ['Underfitting', 'Overfitting', 'Perfect', 'A data-leak fix'],
            answer: 1,
          },
          {
            q: 'Recall answers…',
            options: [
              'Of flagged rows, how many were truly bad?',
              'Of truly bad rows, how many did we catch?',
              'How fast is the model?',
              'How big is the dataset?',
            ],
            answer: 1,
          },
        ],
      },
      {
        id: 'p2-nn',
        title: 'Neural networks, visually',
        kind: 'learn',
        icon: 'Network',
        studyDays: 2,
        tagline: 'Layers of tiny functions that learn by nudging weights.',
        flow: ['Input', 'Hidden layers', 'Output', 'Loss', 'Backprop', 'Update'],
        cards: [
          { icon: 'Network', title: 'Neurons & layers', text: 'Weighted sums + activation, stacked in layers.' },
          { icon: 'TrendingUp', title: 'Gradient descent', text: 'Walk downhill on the error surface, one small step at a time.' },
          { icon: 'Repeat', title: 'Backpropagation', text: 'Blame flows backwards so each weight knows how to change.' },
        ],
        bridge: 'Backprop is root-cause analysis: trace the error back to the step that caused it.',
        build: 'Make the spiral dataset converge in TensorFlow Playground. Screenshot it for your notes.',
        courses: [
          c.nn3b1b,
          c.gd3b1b,
          m.backprop3b1b,
          m.backpropCalc3b1b,
          m.statquestNn,
          c.tfPlayground,
          m.nnSeries3b1b,
          c.micrograd,
          m.fastaiLesson1,
          c.fastai,
          m.zeroToHero,
        ],
        quiz: [
          {
            q: 'Gradient descent does what?',
            options: ['Adds layers', 'Adjusts weights to reduce error step by step', 'Deletes bad data', 'Encrypts the model'],
            answer: 1,
          },
          {
            q: 'Backpropagation computes…',
            options: ['How each weight contributed to the error', 'The dataset size', 'The learning schedule', 'GPU temperature'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p2-embed',
        title: 'Tokens & embeddings',
        kind: 'learn',
        icon: 'Puzzle',
        studyDays: 2,
        tagline: 'Text → tokens → vectors. Meaning becomes geometry.',
        flow: ['Text', 'Tokens', 'Token IDs', 'Vectors', 'Similarity'],
        cards: [
          { icon: 'Puzzle', title: 'Tokens', text: 'LLMs read word pieces, not letters. You pay per token.' },
          { icon: 'Compass', title: 'Embeddings', text: 'Similar meaning = nearby vectors. The heart of search and RAG.' },
          { icon: 'Scale', title: 'Cosine similarity', text: 'The angle between vectors ≈ how related two texts are.' },
        ],
        bridge: "Embeddings are fuzzy join keys: match 'cust_nm' to 'customer name' by meaning.",
        build: 'Embed 20 column names from past projects and list the most similar pairs.',
        courses: [c.karpathyTokenizer, c.tiktokenizer, m.statquestWord2vec, c.word2vec, c.hfLlmCourse],
        quiz: [
          {
            q: 'Two sentences with similar meaning have embeddings that are…',
            options: ['Identical strings', 'Close together in vector space', 'Always orthogonal', 'Random'],
            answer: 1,
          },
          {
            q: 'LLM API pricing is usually per…',
            options: ['Character', 'Token', 'Word document', 'Minute'],
            answer: 1,
          },
        ],
      },
    ],
  },
  {
    id: 'p3',
    order: 3,
    title: 'LLMs & Prompting',
    icon: 'Sparkles',
    hue: 'fuchsia',
    goal: 'Understand LLMs and make them return reliable, structured output.',
    modules: [
      {
        id: 'p3-llm',
        title: 'How LLMs work',
        kind: 'learn',
        icon: 'Cpu',
        studyDays: 3,
        tagline: 'Next-token prediction at massive scale, then tuned to be helpful.',
        flow: ['Pre-training', 'Base model', 'Fine-tuning', 'RLHF', 'Assistant'],
        cards: [
          { icon: 'Cpu', title: 'Transformer', text: 'Attention lets each token look at every other token for context.' },
          { icon: 'Layers', title: 'Context window', text: "The model's working memory: everything it knows about your task." },
          { icon: 'CircleAlert', title: 'Hallucinations', text: 'Confident wrong answers. Why grounding and evals matter.' },
        ],
        bridge: 'Hallucination = silent data corruption. You already know how to hunt those.',
        build: 'Ask 3 LLMs the same tricky SQL question; log the differences in a table.',
        courses: [
          c.llmBrief3b1b,
          m.ibmHowLlmsWork,
          c.karpathyIntroLlm,
          c.transformers3b1b,
          c.attention3b1b,
          m.statquestTransformer,
          c.transformerExplainer,
          c.bbycroft,
          c.dlaiTransformerLlms,
          c.karpathyDeepDive,
          c.karpathyHowIUse,
          c.stateOfGpt,
          c.facts3b1b,
          m.mlabonneCourse,
          c.buildGpt,
          m.reproduceGpt2,
        ],
        quiz: [
          {
            q: 'At its core, an LLM is trained to…',
            options: ['Search Google', 'Predict the next token', 'Run SQL', 'Store facts in tables'],
            answer: 1,
          },
          {
            q: 'Attention helps a token…',
            options: ['Use context from other tokens', 'Compress files', 'Encrypt data', 'Cut GPU cost to zero'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p3-prompt',
        title: 'Prompt engineering',
        kind: 'learn',
        icon: 'MessageSquare',
        studyDays: 3,
        tagline: 'Clear instructions, examples and structure beat clever tricks.',
        flow: ['Role', 'Task', 'Context', 'Examples', 'Output format'],
        cards: [
          { icon: 'Target', title: 'Be specific', text: 'Say exactly what, for whom, in what format. Like a good test case.' },
          { icon: 'ListChecks', title: 'Few-shot', text: 'Show 2–3 examples. The model copies the pattern.' },
          { icon: 'Brain', title: 'Chain-of-thought', text: 'Ask it to reason step by step before answering.' },
        ],
        bridge: 'A prompt is a test spec: preconditions, steps, expected result.',
        build: 'Write a prompt that turns a mapping rule into 3 SQL test cases. Iterate 5 versions with a changelog.',
        courses: [c.dlaiPromptEng, c.anthropicPrompt, m.anthropicPromptDeepDive, m.fccPromptEng, c.promptingGuide, c.learnPrompting],
        quiz: [
          {
            q: 'Few-shot prompting means…',
            options: ['Giving a few examples in the prompt', 'Using a small model', 'Sending fewer requests', 'Short answers only'],
            answer: 0,
          },
          {
            q: 'To reduce hallucinations you should…',
            options: [
              "Give relevant context and allow 'I don't know'",
              'Increase temperature',
              'Remove instructions',
              'Ask it to sound confident',
            ],
            answer: 0,
          },
        ],
      },
      {
        id: 'p3-structured',
        title: 'LLM APIs, structured output & tools',
        kind: 'learn',
        icon: 'Workflow',
        studyDays: 2,
        tagline: 'Turn free text into typed JSON your code can trust.',
        flow: ['Prompt', 'LLM', 'JSON schema', 'Pydantic check', 'Your code'],
        cards: [
          { icon: 'FileText', title: 'Structured outputs', text: 'Force responses to match a JSON schema.' },
          { icon: 'Plug', title: 'Tool calling', text: 'The model picks a function + arguments; your code runs it.' },
          { icon: 'Gauge', title: 'Temperature & tokens', text: 'Low temperature for SQL and tests; cap max tokens for cost.' },
        ],
        bridge: 'Schema-validate LLM output exactly like you validate a file landing in ADLS.',
        build: 'Return a list[TestCase] Pydantic model via Instructor or native structured output.',
        courses: [c.geminiDocs, c.openaiStructured, c.instructor, c.dlaiFunctionsTools, m.ebbelaarAgents],
        quiz: [
          {
            q: 'With tool calling, who actually executes the function?',
            options: ['The LLM provider', 'Your application code', 'The browser', 'Nobody'],
            answer: 1,
          },
          {
            q: 'For deterministic SQL generation, prefer temperature…',
            options: ['Low (0–0.2)', 'High (1.5)', 'Random', 'It does not matter'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p3-mini1',
        title: 'Mini-project 1: Mapping → Test Cases',
        kind: 'project',
        icon: 'Hammer',
        studyDays: 2,
        tagline: 'Your first AI tool: STTM spreadsheet in, SQL test suite out.',
        flow: ['STTM CSV', 'Prompt + schema', 'LLM', 'list[TestCase]', 'SQL files'],
        cards: [
          { icon: 'FileText', title: 'Input', text: 'A source-to-target mapping CSV with transformation rules.' },
          { icon: 'Sparkles', title: 'LLM step', text: 'Generates count, null, duplicate and rule tests.' },
          { icon: 'CircleCheck', title: 'Output', text: 'Validated JSON + runnable SQL, committed to GitHub.' },
        ],
        bridge: 'This is the seed of your capstone — later it becomes the Planner agent.',
        build: 'Ship a CLI: gen_tests.py mapping.csv → tests/*.sql, plus a README with a GIF.',
        courses: [c.duckdb, c.awesomeLlmApps],
        quiz: [
          {
            q: 'Why validate LLM output with Pydantic before writing SQL files?',
            options: ['Catch malformed or missing fields early', 'Make it slower', 'SQL requires Python', 'No reason'],
            answer: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'p4',
    order: 4,
    title: 'RAG & Vector DBs',
    icon: 'Database',
    hue: 'cyan',
    goal: 'Ground LLMs in your own documents and measure answer quality.',
    modules: [
      {
        id: 'p4-vector',
        title: 'Embeddings & vector databases',
        kind: 'learn',
        icon: 'Boxes',
        studyDays: 3,
        tagline: 'Store meaning, search by similarity.',
        flow: ['Documents', 'Embed', 'Vector index', 'Query', 'Top-k matches'],
        cards: [
          { icon: 'Boxes', title: 'Vector DB', text: 'Chroma, pgvector, Azure AI Search: indexes built for similarity.' },
          { icon: 'Search', title: 'Hybrid search', text: 'Keyword (BM25) + vector together gives the best recall.' },
          { icon: 'Filter', title: 'Metadata filters', text: 'Filter by source, date, domain — like a WHERE clause.' },
        ],
        bridge: 'An index is an index: think partitions + WHERE, but on meaning.',
        build: "Load your data dictionary into Chroma; ask 'where is customer email stored?'",
        courses: [c.dlaiVectorDb, m.fireshipVectorDb, m.fccVectorEmbeddings, c.pineconeLearn, c.chroma, c.azureAiSearch],
        quiz: [
          {
            q: 'Hybrid search combines…',
            options: ['Vector + keyword search', 'Two LLMs', 'SQL + Excel', 'CPU + GPU'],
            answer: 0,
          },
          {
            q: 'Metadata filtering is most like…',
            options: ['A SQL WHERE clause', 'A JOIN', 'A trigger', 'A backup'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p4-rag',
        title: 'RAG fundamentals',
        kind: 'learn',
        icon: 'Layers',
        studyDays: 4,
        tagline: 'Retrieve relevant chunks, then let the LLM answer with them.',
        flow: ['Load', 'Chunk', 'Embed', 'Store', 'Retrieve', 'Generate'],
        cards: [
          { icon: 'Rows3', title: 'Chunking', text: 'Split docs into overlapping pieces. Size drives quality.' },
          { icon: 'Search', title: 'Retrieval', text: 'Find the top-k chunks relevant to the question.' },
          { icon: 'Sparkles', title: 'Grounded answer', text: 'The LLM answers only from retrieved context, with citations.' },
        ],
        bridge: 'RAG ingestion is ETL: extract docs, transform to chunks, load to a vector store.',
        build: 'Notebook RAG over 5 Azure Data Factory docs pages, answers with citations.',
        courses: [m.ibmRag, c.fccRag, m.pixegamiRag, c.dlaiChatData, m.brandonLangchain, m.llmZoomcamp, c.courseraRag, c.llamaIndex],
        quiz: [
          {
            q: 'RAG reduces hallucination mainly by…',
            options: ['Giving the model relevant source text at query time', 'Retraining nightly', 'Bigger GPUs', 'Lower token cost'],
            answer: 0,
          },
          {
            q: 'Chunks that are too large tend to…',
            options: ['Dilute relevance and waste context', 'Always improve answers', 'Crash the vector DB', 'Reduce latency'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p4-advanced',
        title: 'Advanced RAG & evaluation',
        kind: 'learn',
        icon: 'FlaskConical',
        studyDays: 3,
        tagline: 'Measure faithfulness and relevance — then improve retrieval.',
        flow: ['Question', 'Retrieve', 'Re-rank', 'Answer', 'Evaluate'],
        cards: [
          { icon: 'FlaskConical', title: 'RAG triad', text: 'Context relevance, groundedness, answer relevance.' },
          { icon: 'Shuffle', title: 'Re-ranking', text: 'A second model re-orders chunks for precision.' },
          { icon: 'ListChecks', title: 'Golden dataset', text: 'Q&A pairs with expected answers = your regression suite.' },
        ],
        bridge: "Golden datasets are expected-results tables. You're the expert here.",
        build: 'Create 15 golden Q&A pairs; score your RAG with Ragas before and after re-ranking.',
        courses: [c.dlaiAdvancedRag, c.dlaiAdvancedRetrieval, m.kamradtSplitting, m.jerryLiuRag, c.ragas, c.dlaiAgenticRag],
        quiz: [
          {
            q: 'Groundedness (faithfulness) checks whether…',
            options: ['The answer is supported by retrieved context', 'The UI is responsive', 'Chunks are short', 'The model is open source'],
            answer: 0,
          },
          {
            q: 'A RAG golden dataset is most like…',
            options: ['Expected results for regression tests', 'A backup', 'A cache', 'A prompt template'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p4-mini2',
        title: 'Mini-project 2: Data-docs RAG chatbot',
        kind: 'project',
        icon: 'Hammer',
        studyDays: 3,
        tagline: 'Chat with ADF / Databricks / Informatica docs and your mapping specs.',
        flow: ['Docs + STTM', 'Chunk + embed', 'Chroma', 'Retriever', 'Chat UI', 'Eval score'],
        cards: [
          { icon: 'MessageSquare', title: 'Chat UI', text: 'Streamlit chat with source citations.' },
          { icon: 'FlaskConical', title: 'Eval badge', text: 'Ragas scores shown in the README.' },
          { icon: 'Rocket', title: 'Portfolio ready', text: 'Public repo with a GIF demo.' },
        ],
        bridge: 'This becomes the knowledge layer of your capstone.',
        build: "Ship repo 'data-docs-rag' with Streamlit UI, 15-question eval and a results table.",
        courses: [c.streamlit, c.chroma, m.pixegamiRag, c.ragas],
        quiz: [
          {
            q: 'Why show citations in a RAG chatbot?',
            options: ['Users can verify answers against sources', 'It looks nicer', 'It reduces tokens', 'Python requires it'],
            answer: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'p5',
    order: 5,
    title: 'Agents & Agentic AI',
    icon: 'Bot',
    hue: 'amber',
    goal: 'Build LLM systems that plan, use tools and collaborate — safely.',
    modules: [
      {
        id: 'p5-agents',
        title: 'Agent fundamentals',
        kind: 'learn',
        icon: 'Bot',
        studyDays: 3,
        tagline: 'An agent = LLM + tools + a loop: think, act, observe.',
        flow: ['Goal', 'Think', 'Act (tool)', 'Observe', 'Repeat', 'Answer'],
        cards: [
          { icon: 'Repeat', title: 'ReAct loop', text: 'Reason, call a tool, read the result, decide the next step.' },
          { icon: 'Wrench', title: 'Tools', text: 'Functions the agent may call: SQL, search, APIs, files.' },
          { icon: 'Workflow', title: 'Workflow vs agent', text: 'Fixed steps vs model-decided steps. Start simple.' },
        ],
        bridge: 'Agents are orchestration pipelines where the LLM picks the next activity — ADF with a brain.',
        build: 'Build a tool-calling agent with two tools: get_schema and run_sql (read-only).',
        courses: [c.hfAgents, c.msAgentsBeginners, m.ibmAgents, m.barryZhangAgents, c.anthropicAgents, m.ebbelaarAgents, c.ngAgenticTalk],
        quiz: [
          {
            q: 'Which is the ReAct loop?',
            options: ['Reason → Act → Observe', 'Read → Archive → Close', 'Request → Approve → Commit', 'Render → Animate → Cache'],
            answer: 0,
          },
          {
            q: "Anthropic's guidance: start with…",
            options: ['The simplest workflow that works', 'A 10-agent swarm', 'Fine-tuning', 'No tools'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p5-agentic',
        title: 'Agentic AI design patterns',
        kind: 'learn',
        icon: 'Lightbulb',
        studyDays: 3,
        tagline: "Reflection, tool use, planning, multi-agent — Andrew Ng's four patterns.",
        flow: ['Reflection', 'Tool use', 'Planning', 'Multi-agent'],
        cards: [
          { icon: 'Eye', title: 'Reflection', text: 'The model critiques and fixes its own output.' },
          { icon: 'Route', title: 'Planning', text: 'Break a goal into steps, then execute them.' },
          { icon: 'Users', title: 'Multi-agent', text: 'Specialist agents collaborate, like a delivery team.' },
        ],
        bridge: 'Reflection = peer review of test cases. Planning = test strategy before execution.',
        build: 'Add a reflection step: the agent reviews its generated SQL tests and fixes issues.',
        courses: [c.ngAgenticAi, c.kaggleAgents, m.harrisonAgents, c.openaiAgentsSdk],
        quiz: [
          {
            q: 'The reflection pattern means…',
            options: ['The agent critiques and revises its own output', 'Mirroring a database', 'Caching responses', 'Dark mode'],
            answer: 0,
          },
          {
            q: 'Planning helps an agent…',
            options: ['Decompose a goal into ordered steps', 'Avoid tools', 'Skip evaluation', 'Guess faster'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p5-langgraph',
        title: 'LangGraph: stateful agent graphs',
        kind: 'learn',
        icon: 'Workflow',
        studyDays: 4,
        tagline: 'Agents as graphs: nodes, edges, shared state, checkpoints.',
        flow: ['State', 'Node', 'Conditional edge', 'Tool node', 'Checkpoint', 'Human approval'],
        cards: [
          { icon: 'Workflow', title: 'Graph = pipeline', text: 'Nodes are steps, edges are routing — like an ADF pipeline canvas.' },
          { icon: 'Database', title: 'Persistence', text: 'Checkpoints let runs pause, resume and time-travel.' },
          { icon: 'Users', title: 'Human-in-the-loop', text: 'Interrupt before risky actions; a human approves.' },
        ],
        bridge: "You've read pipeline DAGs for a decade. LangGraph is a DAG (with loops) for LLMs.",
        build: 'Port your agent to LangGraph with an approval interrupt before any SQL runs.',
        courses: [c.langchainAcademy, c.dlaiLanggraph, m.fccLanggraph, c.langgraphDocs],
        quiz: [
          {
            q: 'In LangGraph, conditional edges…',
            options: ['Route to the next node based on state', 'Style the graph', 'Compress state', 'Encrypt tools'],
            answer: 0,
          },
          {
            q: 'Why add a human-in-the-loop interrupt?',
            options: ['Approve risky actions like writes or costly queries', 'Make it slower', 'Required on all nodes', 'To train the model'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p5-multi',
        title: 'Multi-agent systems',
        kind: 'learn',
        icon: 'Users',
        studyDays: 2,
        tagline: 'Planner, worker, reviewer: split big jobs across specialists.',
        flow: ['Supervisor', 'Planner', 'SQL agent', 'Reviewer', 'Report'],
        cards: [
          { icon: 'Users', title: 'Roles & goals', text: 'Each agent has one job and its own tools.' },
          { icon: 'Network', title: 'Supervisor pattern', text: 'One agent routes work to the others.' },
          { icon: 'CircleAlert', title: 'Costs & loops', text: 'More agents = more tokens and failure modes. Measure.' },
        ],
        bridge: 'Just like your QA team: lead plans, testers execute, reviewer signs off.',
        build: "Diagram your capstone's 4 agents and their tools in the repo README.",
        courses: [c.dlaiCrewai, c.msAgentsBeginners, m.langgraphMultiAgent],
        quiz: [
          {
            q: 'A supervisor agent…',
            options: ['Routes tasks to specialist agents', 'Stores embeddings', 'Hosts the API', 'Formats markdown'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p5-mcp',
        title: 'MCP: plug tools into any agent',
        kind: 'learn',
        icon: 'Plug',
        studyDays: 2,
        tagline: 'Model Context Protocol = USB-C for AI tools and data.',
        flow: ['Agent (client)', 'MCP protocol', 'MCP server', 'Your DB / APIs'],
        cards: [
          { icon: 'Plug', title: 'Standard connector', text: 'Write a tool server once; use it from Claude, Copilot or LangGraph.' },
          { icon: 'Server', title: 'Tools, resources, prompts', text: 'The three primitives an MCP server exposes.' },
          { icon: 'Lock', title: 'Least privilege', text: 'Expose read-only, scoped tools. Never raw admin access.' },
        ],
        bridge: 'An MCP server is like a linked service + stored-procedure layer for agents.',
        build: 'Write an MCP server exposing get_schema and run_readonly_sql over DuckDB.',
        courses: [c.dlaiMcp, c.hfMcp, m.maheshMcp, c.mcpDocs],
        quiz: [
          {
            q: 'MCP mainly standardises…',
            options: ['How agents connect to tools and data', 'GPU cooling', 'Model training', 'CSS styling'],
            answer: 0,
          },
          {
            q: 'Safest DB tool to expose to an agent?',
            options: ['Read-only, scoped queries', 'Full admin', 'DROP TABLE', 'Shell access'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p5-mini3',
        title: 'Mini-project 3: SQL validation agent',
        kind: 'project',
        icon: 'Hammer',
        studyDays: 3,
        tagline: 'An agent that reads a mapping, writes tests, runs them, explains failures.',
        flow: ['Mapping', 'Plan tests', 'Generate SQL', 'Run via MCP', 'Explain'],
        cards: [
          { icon: 'Bot', title: 'LangGraph agent', text: 'Planner → SQL → Executor → Analyst.' },
          { icon: 'ShieldCheck', title: 'Guardrails', text: 'Read-only SQL, row limits, human approval.' },
          { icon: 'FileText', title: 'Report', text: 'Markdown test report with pass/fail and root-cause hints.' },
        ],
        bridge: 'This IS capstone v0.1. The next phases harden, evaluate and deploy it.',
        build: 'Ship DataSentinel AI v0.1 locally on DuckDB sample data.',
        courses: [c.langgraphDocs, c.duckdb, c.mcpDocs],
        quiz: [
          {
            q: 'Why run generated SQL through a read-only tool?',
            options: ['Prevent destructive or unintended writes', 'Faster queries', 'Better formatting', 'SQL requires it'],
            answer: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'p6',
    order: 6,
    title: 'LLMOps & Azure',
    icon: 'Cloud',
    hue: 'rose',
    goal: 'Test, secure, observe and ship AI on Azure — your QA superpower.',
    modules: [
      {
        id: 'p6-evals',
        title: 'LLM evaluation & testing',
        kind: 'learn',
        icon: 'FlaskConical',
        studyDays: 3,
        tagline: "If you can't measure it, you can't ship it.",
        flow: ['Test cases', 'Run app', 'LLM-as-judge', 'Thresholds', 'CI gate'],
        cards: [
          { icon: 'FlaskConical', title: 'Evals = tests', text: 'Unit tests for prompts, regression sets for agents.' },
          { icon: 'Scale', title: 'LLM-as-judge', text: 'A model grades outputs against a rubric.' },
          { icon: 'ShieldCheck', title: 'CI gates', text: 'Block merges when quality drops. Pure QA.' },
        ],
        bridge: 'This is where 10 years of testing makes you stand out from other candidates.',
        build: 'Add a 10-case DeepEval suite to your agent and run it in GitHub Actions.',
        courses: [c.dlaiTestingLlmops, c.deepeval, c.hamelEvals, m.lennyEvals, c.dlaiEvalDebug, m.llmZoomcamp],
        quiz: [
          {
            q: 'LLM-as-a-judge means…',
            options: ['An LLM scores outputs against criteria', 'A court case', 'Human-only review', 'A Python syntax test'],
            answer: 0,
          },
          {
            q: 'An eval CI gate should…',
            options: ['Fail the build when scores drop below thresholds', 'Always pass', 'Run yearly', 'Delete failing tests'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p6-safety',
        title: 'Guardrails, security & observability',
        kind: 'learn',
        icon: 'ShieldCheck',
        studyDays: 2,
        tagline: 'Prompt injection, PII, cost, traces — production-grade AI.',
        flow: ['User input', 'Input guard', 'LLM / agent', 'Output guard', 'Trace + cost'],
        cards: [
          { icon: 'Bug', title: 'Prompt injection', text: 'Untrusted text can hijack instructions. Treat inputs as hostile.' },
          { icon: 'Lock', title: 'PII & secrets', text: 'Mask sensitive data before it reaches the model.' },
          { icon: 'Eye', title: 'Tracing', text: 'Langfuse shows every step, token and cost.' },
        ],
        bridge: 'Same as data masking and audit logging in your DWH projects.',
        build: 'Add Langfuse tracing and a prompt-injection test case to your agent.',
        courses: [c.owaspLlm, m.ibmPromptInjection, c.dlaiQualitySafety, c.langfuse],
        quiz: [
          {
            q: 'Prompt injection is…',
            options: ['Untrusted input overriding your instructions', 'A faster prompt', 'A type of fine-tuning', 'SQL indexing'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p6-docker',
        title: 'Docker & containers',
        kind: 'learn',
        icon: 'Container',
        studyDays: 2,
        tagline: 'Package your app once; run it anywhere.',
        flow: ['Code', 'Dockerfile', 'Image', 'Container', 'Registry'],
        cards: [
          { icon: 'Container', title: 'Image vs container', text: 'Recipe vs the dish being served.' },
          { icon: 'Layers', title: 'Layers & caching', text: 'Order Dockerfile steps for fast rebuilds.' },
          { icon: 'Boxes', title: 'Compose', text: 'Run API + vector DB together locally.' },
        ],
        bridge: 'Containers are like deployment groups — the same artifact across DEV, QA and PROD.',
        build: 'Dockerize your FastAPI agent service and run it with docker compose.',
        courses: [m.fireshipDocker, m.fireshipDockerConcepts, c.nanaDocker, m.fccDocker, c.dockerGetStarted],
        quiz: [
          {
            q: 'A Docker image is…',
            options: ['A read-only template used to create containers', 'A running process', 'A VM', 'A database'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p6-azure',
        title: 'Azure AI Foundry & deployment',
        kind: 'learn',
        icon: 'Cloud',
        studyDays: 4,
        tagline: 'Azure OpenAI + AI Search + Container Apps = your production stack.',
        flow: ['Azure OpenAI', 'AI Search', 'Container Apps', 'Key Vault', 'App Insights'],
        cards: [
          { icon: 'Cloud', title: 'Azure AI Foundry', text: 'Model catalog, deployments, playground and evals in one portal.' },
          { icon: 'Server', title: 'Container Apps', text: 'Serverless containers; scale to zero to save credit.' },
          { icon: 'Lock', title: 'Managed identity', text: 'No keys in code — services authenticate each other.' },
        ],
        bridge: 'You know ADF, ADLS and Databricks — this is the same Azure, new services.',
        build: 'Deploy the DataSentinel API to Azure Container Apps using Azure OpenAI + AI Search.',
        tip: 'Activate the Azure free account at the start of this phase — the credit is time-limited.',
        courses: [c.msGenAiBeginners, c.msLearnGenAi, m.az900, c.azureFoundry, c.azureContainerApps],
        quiz: [
          {
            q: 'Why use managed identity?',
            options: ['Services authenticate without secrets in code', 'Faster GPUs', 'Cheaper tokens', 'Nicer UI'],
            answer: 0,
          },
          {
            q: 'To save credit on Container Apps…',
            options: ['Allow scale to zero', 'Pin 10 replicas', 'Disable logging only', 'Use bigger CPUs'],
            answer: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'p7',
    order: 7,
    title: 'Capstone Launch',
    icon: 'Trophy',
    hue: 'orange',
    goal: 'Polish, prove and publish DataSentinel AI — your flagship project.',
    modules: [
      {
        id: 'p7-integrate',
        title: 'Integrate & harden',
        kind: 'project',
        icon: 'Workflow',
        studyDays: 4,
        tagline: 'All pieces together: RAG + agents + MCP + evals on Azure.',
        flow: ['Mapping docs', 'RAG', 'LangGraph agents', 'MCP → Databricks', 'Report UI'],
        cards: [
          { icon: 'Network', title: 'End-to-end', text: 'One click from mapping doc to an explained test report.' },
          { icon: 'Database', title: 'Real platform', text: 'Run against Databricks SQL sample data.' },
          { icon: 'ShieldCheck', title: 'Hardened', text: 'Read-only guardrails, retries, cost limits.' },
        ],
        bridge: 'Your domain + AI = a niche few candidates can show.',
        build: "Close every 'P7' item on the capstone board.",
        courses: [c.databricksFree, c.langgraphDocs, c.azureContainerApps],
        quiz: [
          {
            q: 'Before a demo, what matters most?',
            options: ['A reliable, repeatable happy path backed by evals', 'Max number of agents', 'Longest prompt', 'Newest model only'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p7-prove',
        title: 'Prove it: evals & metrics',
        kind: 'project',
        icon: 'Gauge',
        studyDays: 3,
        tagline: 'Numbers recruiters remember: accuracy, cost, time saved.',
        flow: ['Golden set', 'Eval run', 'Scores', 'Before / after', 'README table'],
        cards: [
          { icon: 'Gauge', title: 'Quality', text: 'Test-case correctness %, faithfulness, pass rate.' },
          { icon: 'Clock', title: 'Time saved', text: 'Manual hours vs agent minutes per mapping.' },
          { icon: 'TrendingUp', title: 'Cost', text: '$ per validation run, tokens per step.' },
        ],
        bridge: "Frame it like a QA metrics report — you've written dozens.",
        build: 'Publish an eval results table and a cost / time-saved chart in the README.',
        courses: [c.deepeval, c.hamelEvals, c.langfuse],
        quiz: [
          {
            q: 'Best capstone headline metric?',
            options: ['Time saved per mapping, with measured accuracy', 'Number of files', 'Lines of code', 'Colours used'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p7-launch',
        title: 'Launch kit: README, demo, posts',
        kind: 'project',
        icon: 'Rocket',
        studyDays: 4,
        tagline: "Great work nobody sees doesn't get you hired.",
        flow: ['Diagram', 'README', '3-min demo', 'Blog post', 'LinkedIn'],
        cards: [
          { icon: 'FileText', title: 'README', text: 'Problem, architecture diagram, quick start, metrics, roadmap.' },
          { icon: 'Video', title: 'Demo video', text: '3 minutes: problem → live run → results.' },
          { icon: 'Globe', title: 'Share', text: 'Blog + LinkedIn post tagged with the tools you used.' },
        ],
        bridge: "Your story: 'I tested data platforms for 10 years; now I build AI that tests them.'",
        build: 'Publish README, demo video, blog post and LinkedIn post. Update your résumé.',
        courses: [c.makeReadme, c.mermaid, c.demoVideo],
        quiz: [
          {
            q: 'What should come first in your README?',
            options: ['The problem it solves + a demo GIF', 'The licence', 'Every dependency', 'Commit history'],
            answer: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'p8',
    order: 8,
    title: 'Job-Ready Sprint',
    icon: 'Briefcase',
    hue: 'indigo',
    buffer: true,
    goal: 'Days 91–120: interviews, credentials, fine-tuning, applications.',
    modules: [
      {
        id: 'p8-sysdesign',
        title: 'LLM system design',
        kind: 'learn',
        icon: 'Network',
        studyDays: 6,
        tagline: 'Explain trade-offs: latency, cost, quality, safety.',
        flow: ['Requirements', 'Architecture', 'RAG / agents', 'Evals', 'Scale & cost'],
        cards: [
          { icon: 'Network', title: 'Reference architectures', text: 'Gateway, cache, router, guardrails, observability.' },
          { icon: 'Scale', title: 'Trade-offs', text: 'Big model vs latency; RAG vs fine-tune; agent vs workflow.' },
          { icon: 'MessageSquare', title: 'Talk it through', text: 'Practise whiteboarding aloud in 30 minutes.' },
        ],
        bridge: "You've reviewed data-platform designs — same muscles, new components.",
        build: 'Whiteboard 3 designs: support chatbot, doc Q&A, data-quality agent.',
        courses: [c.huyenPlatform, m.jerryLiuRag, m.barryZhangAgents, c.aieBook, c.sysDesignVideo],
        quiz: [
          {
            q: 'When is fine-tuning preferred over RAG?',
            options: [
              'To change style, format or behaviour — not to add fresh facts',
              'To add knowledge that changes daily',
              'Never',
              'Always',
            ],
            answer: 0,
          },
        ],
      },
      {
        id: 'p8-finetune',
        title: 'Fine-tuning basics (LoRA)',
        kind: 'learn',
        icon: 'Wrench',
        studyDays: 5,
        tagline: 'Teach a small model a narrow skill, cheaply.',
        flow: ['Dataset', 'Base model', 'LoRA adapters', 'Train (Colab)', 'Evaluate'],
        cards: [
          { icon: 'Wrench', title: 'LoRA / QLoRA', text: 'Train tiny adapter weights instead of the whole model.' },
          { icon: 'Cpu', title: 'Free GPUs', text: 'Google Colab + Unsloth notebooks on free T4 GPUs.' },
          { icon: 'FlaskConical', title: 'Evaluate first', text: 'Fine-tune only after prompting + RAG hit a ceiling.' },
        ],
        bridge: 'Training-data quality decides everything — your core expertise.',
        build: 'Fine-tune a small model to turn mapping rules into SQL; compare with prompting.',
        courses: [c.dlaiFinetune, m.umarLora, m.shawFinetune, c.unsloth, m.mlabonneCourse, c.hfLlmCourse],
        quiz: [
          {
            q: 'LoRA reduces cost by…',
            options: ['Training small adapter matrices instead of all weights', 'Deleting layers', 'CPUs only', 'Skipping evaluation'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p8-cert',
        title: 'Free credentials',
        kind: 'learn',
        icon: 'Award',
        studyDays: 6,
        tagline: 'Recruiter signals: free badges and certificates.',
        flow: ['HF Agents cert', 'HF MCP cert', 'Kaggle certs', 'MS Applied Skills', 'LinkedIn'],
        cards: [
          { icon: 'Award', title: 'Hugging Face', text: 'Free certificates for the Agents and MCP courses.' },
          { icon: 'GraduationCap', title: 'MS Applied Skills', text: 'Free, lab-based Azure AI credentials.' },
          { icon: 'Medal', title: 'Kaggle', text: 'Free micro-course certificates.' },
        ],
        bridge: 'Later (paid, optional): Databricks GenAI Engineer Associate fits your Databricks years.',
        build: 'Earn at least 2 free credentials and add them to LinkedIn.',
        courses: [c.msAppliedSkills, c.hfAgents, c.hfMcp],
        quiz: [
          {
            q: 'Which credential is free and lab-based on Azure?',
            options: ['Microsoft Applied Skills', 'A paid bootcamp', 'None exist', 'Only degrees'],
            answer: 0,
          },
        ],
      },
      {
        id: 'p8-interview',
        title: 'Interview prep',
        kind: 'learn',
        icon: 'Mic',
        studyDays: 5,
        tagline: 'Tell the tester → AI engineer story with confidence.',
        flow: ['Story', 'Project deep-dive', 'Concepts', 'System design', 'Behavioural'],
        cards: [
          { icon: 'Mic', title: 'Your story', text: '60-second pitch: data-quality roots → AI builder.' },
          { icon: 'Hammer', title: 'Project deep-dive', text: 'Explain every decision in DataSentinel AI.' },
          { icon: 'Repeat', title: 'Mock interviews', text: 'Practise with an LLM interviewer, then with humans.' },
        ],
        bridge: "Reframe: 'I validated pipelines' → 'I build and evaluate reliable data + AI systems.'",
        build: 'Do 3 mock interviews (1 AI, 2 human). Log weak spots in the Career hub.',
        courses: [c.interviewVideo, c.techInterviewHandbook, c.huyenPlatform],
        quiz: [
          {
            q: "Strongest answer to 'Why AI engineering?'",
            options: [
              'A concrete project story showing impact + your data-quality edge',
              "'It pays more'",
              "'Everyone is doing it'",
              "'I like ChatGPT'",
            ],
            answer: 0,
          },
        ],
      },
      {
        id: 'p8-hunt',
        title: 'Job hunt sprint',
        kind: 'learn',
        icon: 'Briefcase',
        studyDays: 3,
        tagline: 'Target, apply, follow up — tracked like a test cycle.',
        flow: ['Target list', 'Tailored résumé', 'Apply', 'Follow up', 'Interview'],
        cards: [
          { icon: 'Target', title: 'Target roles', text: 'AI Engineer, GenAI Engineer, AI Evals/Quality Engineer, Data+AI Engineer.' },
          { icon: 'FileText', title: 'Tailor', text: 'Mirror job-ad keywords with honest project evidence.' },
          { icon: 'TrendingUp', title: 'Track', text: 'Log every application in the Career hub tracker.' },
        ],
        bridge: "'AI Evaluation Engineer' roles are a perfect bridge job for you.",
        build: 'Apply to 5 roles per week and log each one in the tracker.',
        courses: [c.baraaRoadmap, c.techInterviewHandbook],
        quiz: [
          {
            q: 'Which role title is a natural bridge from QA to AI?',
            options: ['AI Evaluation / Quality Engineer', 'Frontend animator', 'Network admin', 'Sales rep'],
            answer: 0,
          },
        ],
      },
    ],
  },
];
